### ISSUE TITLE
Add an option to specify properties prefix

### ISSUE THREAD

**Issue by alonbl** [FasterXML/jackson-dataformats-text#100]
Hi,

Properties may have a prefix for an object, for example:
```
a.b.c.name =
a.b.c.id =
x.y.z.name =
x.y.z.color =
```

It would be nice if a prefix can be specified, so that only these properties with the prefix will be loaded, prefix will be stripped and then business as usual. When writing, the prefix will be added.

This will allow reading system properties and complex file properties using this interface quite easily and replace many of the complex properties processing.

If this is acceptable, I can workout a patch.

Thanks!

**Comment by dharezlak** [comment]
Can this be configured somehow with the current configuration options? I am interested in writing properties with a common prefix to a file.

**Comment by alonbl** [comment]
I could not find, a workaround:

```java
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.dataformat.yaml.*;
import java.util.*;

public class T {

     static class Test {
           @JsonProperty
           int field1 = 44;
     }

     public static Object nestObject(Object o, List<String> levels) {
           if (levels.size() == 0) {
                return o;
           }
           else {
                return Collections.singletonMap(levels.get(0), nestObject(o, levels.subList(1, levels.size())));
           }
     }

     public static Object nestObject(Object o, String... levels) {
           return nestObject(o, Arrays.asList(levels));
     }

     public static void main(String... args) throws Exception {
           ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
           System.out.println(mapper.writeValueAsString(nestObject(new Test(), "a", "b", "c")));
     }
}
```

**Comment by dharezlak** [comment]
I successfully used `withRootName()` for the writing case:

```
JavaPropsMapper mapper = new JavaPropsMapper();
mapper
	.writerFor(Bean.class)
	.with(JavaPropsSchema
			.emptySchema()
			.withKeyValueSeparator(" = ")
			.withWriteIndexUsingMarkers(true)
			.withFirstArrayOffset(0)
			.withIndexMarker(Markers.create("[", "]")))
	.withRootName("root.subroot")
	.writeValueAsString(bean);
```

**Comment by cowtowncoder** [comment]
This sounds reasonable to me; useful thing. I would be interested in a PR -- ideally against `2.10` branch, since this seems like an incremental feature that need not wait until 3.0.

I could see this working either via reuse of "root name" concept, or, as a new property of `JavaPropsSchema`.

**Comment by alonbl** [comment]
@cowtowncoder this is a draft as a base for discussion at #105 .

I did not use the withRootName as it seems to me that it should be altered at core to support multiple nodes, for example for json/yaml/properties to have a nested prefix and not a single one, to resolve the problem in a generic manner.

For example, I would expect to be able to produce a yaml at nested level with root prefix ["prefix1", "prefix2", "prefix3"]:

```yaml
prefix1:
  prefix2:
    prefix3:
       name: Bob 
```

Please tell me what you think.

**Comment by alonbl** [comment]
Hi @cowtowncoder any chance you review?

**Comment by linyzh** [comment]
带前缀的YAML解析方式
http://yzhlin.lofter.com/post/81657_12de54887?act=qbbloglofter_20150506_01

**Comment by cowtowncoder** [comment]
Missed this one earlier, but will add to my WIP page to hopefully review:

    https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress

**Comment by linyzh** [comment]
审阅通过

At 2019-02-22 09:09:46, "Tatu Saloranta" <notifications@github.com> wrote:


Missed this one earlier, but will add to my WIP page to hopefully review:

https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress

**Comment by cowtowncoder** [comment]
@alonbl Apologies for ultra-slow review. I think I would like to (finally!) proceed, and unless I've asked for and received it, would need CLA:

    https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

which only needs to be sent once for all contributions. Usual way is to print, fill & sign, scan, email to `info` at fasterxml dot com.
Once this is done, I can do merge, possible post-cleanup, and this can make it in 2.10.0.

**Comment by alonbl** [comment]
Sent, thanks!

**Comment by mistriel** [comment]
> Nice, I need it mostly for reading. Of course I can read into Map<String, Object> and then convert value the value of the nested object, however, I believe this feature can be very useful.

Still you can use the same trick for reading:

```
Bean bean = mapper.readerFor(Bean.class)
                    .withRootName("x.y.z")
                    .readValue(inputStream);

```

**Comment by cdprete** [comment]
How is this supposed to work exactly?

I've the following:
```
private static final ObjectMapper objectMapper = new ObjectMapper(new YAMLFactory()).configure(FAIL_ON_UNKNOWN_PROPERTIES, false);

    public static <T> T loadProperties(String prefix, Class<T> clazz, Resource resource) throws IOException {
        Assert.notNull(resource, "The resource to load cannot be null");
        Assert.isTrue(resource.exists() && resource.isReadable(), "The resource to load must exist and it must be readable");

        final ObjectReader reader = readerFor(prefix, clazz);
        final ObjectWriter writer = writerFor(prefix, clazz);

        T value = reader.readValue(resource.getInputStream());
        String yaml = writer.writeValueAsString(value);
        yaml = SystemPropertyUtils.resolvePlaceholders(yaml, true);

        return reader.readValue(yaml);
    }

    private static <T> ObjectReader readerFor(String prefix, Class<T> clazz) {
        ObjectReader reader = objectMapper.readerFor(clazz);
        if(prefix != null && !prefix.isBlank()) {
            reader = reader.withRootName(prefix);
        }

        return reader;
    }

    private static <T>ObjectWriter writerFor(String prefix, Class<T> clazz) {
        ObjectWriter writer = objectMapper.writerFor(clazz);
        if(prefix != null && !prefix.isBlank()) {
            writer = writer.withRootName(prefix);
        }

        return writer;
    }
```
and when I load, let's say, a file `test.yaml` with in `prefix.foo: bar` it fails with:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name ('prefix.foo') does not match expected ('prefix') for type `foo.PropertiesLoaderTest$Foo`
 at [Source: (BufferedInputStream); line: 1, column: 1] (through reference chain: foo.PropertiesLoaderTest$Foo["prefix.foo"])
```

**Comment by cowtowncoder** [comment]
@cdprete I am not sure how what you show is in related to this issue -- issues for Java properties format backend, not YAML.

**Comment by cdprete** [comment]
> @cdprete I am not sure how what you show is in related to this issue -- issues for Java properties format backend, not YAML.

Any plan to have it also for YAML files?

**Comment by cowtowncoder** [comment]
@cdprete I don't think there is a specific plan. I think databind has a request for `@JsonWrapped` (as reverse of `@JsonUnwrapped`), see:

https://github.com/FasterXML/jackson-databind/issues/512

which might cover this -- but no work done for that. It is highly voted-for fwtw .
