### ISSUE TITLE
yaml map keys separated with a point are concatenated

### ISSUE THREAD

**Issue by judos** [FasterXML/jackson-dataformats-text#103]
The following yaml file seems to be read incorrectly:
```
roles:
  OttoUser.permissions:
      login: [GET]
```

Instead of getting the key 'OttoUser' in roles, I get 'OttoUser.permissions'. Of course this then leads to an error when jackson tries to match the 'login: [GET]' to the attribute permissions and fails with an error

The roles object is a Map which maps roles (e.g. 'OttoUser') to another object 'RolePermission'.
The 'RolePermission' object again is a map which maps resources (e.g. 'login') to an array of permissions (e.g. [GET] or [GET, POST]).

```
UnrecognizedPropertyException: Unrecognized field "login" (class RolePermission), not marked as ignorable (one known property: "permissions"])
 at [Source: (File); line: 3, column: 15] (through reference chain: RestAuthRole["roles"]->java.util.LinkedHashMap["OttoUser.permissions"]->RolePermission["login"])
```

If I change the yaml configuration a little bit it works again:
```
roles:
  OttoUser:
    permissions:
      login: [GET]
```
Usually this yaml and the one at the top represents the same data, however jackson treats it differently.

Is it a bug or intended behavior?

**Comment by cowtowncoder** [comment]
I am not an expert in YAML format itself, so just to make sure: does YAML specification indicate that period/point (`.`) may be used as as a short cut this way? Otherwise I would just expect it to be part of property name, the way code in your example works.

**Comment by cowtowncoder** [comment]
Skimming through  YAML spec (1.1, and also 1.2), I don't see anything indicating that period character has special significance in mapping names (property names), so I don't think this is expected handling for YAML documents in general.

Some other data formats (and config libraries, in particular) do allow such shortcuts, so maybe you are thinking some specific use case?

**Comment by judos** [comment]
You are right, I was probably thinking to much about .properties files earlier. I also didn't find anything in the yaml spec.
