### ISSUE TITLE
Element documentation refering to itself

### ISSUE THREAD

**Issue by fbacchella** [FasterXML/jackson-dataformats-text#113]
At https://github.com/FasterXML/jackson-dataformats-text/blob/70407e4a5a54f519ca374a2c557ecb5ddd4f733f/csv/src/main/java/com/fasterxml/jackson/dataformat/csv/CsvParser.java#L117:

That's the documentation for the feature INSERT_NULLS_FOR_MISSING_COLUMNS. And it says :
```
Note that this feature is only considered if INSERT_NULLS_FOR_MISSING_COLUMNS is disabled.
```

Don't we have an infinite loop here ?

**Comment by cowtowncoder** [comment]
Yes, that should be `FAIL_ON_MISSING_COLUMNS`. Not sure how I missed this issue; will fix javadocs. Thanks!
