### ISSUE TITLE
Error handling "null" String when Feature.MINIMIZE_QUOTES is active

### ISSUE THREAD

**Issue by stefanleh** [FasterXML/jackson-dataformats-text#116]
When serializing a String with content "null" and Feature.MINIMIZE_QUOTES is active the "null" value does not get quoted. Therefore when deserializing the value is not a String but **_null_**.

In com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeString(String) there is a special handling for boolean content like "true" and "false". Therefore id suggest to add special handling for "null" and "NULL" string values there as well.

What do you think about that?

**Comment by cowtowncoder** [comment]
Sorry, I had missed this one. Adding on my W-I-P list. Sounds like worthy addition, yes.

**Comment by cowtowncoder** [comment]
Thank you for reporting this, suggesting the fix. I manually merged fix in `2.10`, will be in 2.10.0
