### ISSUE TITLE
`readValues(null)` causes infinite loop

### ISSUE THREAD

**Issue by andyeko** [FasterXML/jackson-dataformats-text#122]
>     @Test
>     public void testEmptyStream() throws InterruptedException {
>         log.info("Start");
>         SimpleModule module = new SimpleModule();
>         CsvMapper csvMapper = new CsvMapper();
>         csvMapper.registerModule(module);
>         try {
>             InputStreamReader reader = null;
>             CsvSchema columns = CsvSchema.emptySchema().withHeader().withColumnSeparator(';');
>             csvMapper.readerFor(Map.class).with(columns).readValues(reader);
>         } catch (IOException e) {
>             log.warn("Can't read data from csv file {}", e);
>         }
>         log.info("finish");
>     }

provided code can freeze execution of the thread completely 
tested with: 2.9.8 version

**Comment by cowtowncoder** [comment]
Interesting. Let me see if I can reproduce.

**Comment by cowtowncoder** [comment]
Yes, seems to get into infinite loop somewhere. Will need to check out stack trace for more info.
