### ISSUE TITLE
Weird behavior with naming?

### ISSUE THREAD

**Issue by alturkovic** [FasterXML/jackson-dataformats-text#127]
Not sure if this is just CSV issue, haven't tested enough, but there is some weird serialization behavior going on that depends on whether property names begin with a single letter before a capitalized word? Not sure exactly what causes it, but the following example demonstrates the problem:

```
@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonPropertyOrder({"aName"})
public class MyClass {

  @JsonProperty("aName")
  private String aName;
}
```
If I run this through the following code:
```
System.out.println(new CsvMapper().writerWithSchemaFor(MyClass.class).writeValueAsString(new MyClass("test")));
```
I get the following result: `test,test`. The field is deserialized twice. If I rename the property to `anName`, I get `test` as expected. Also, if you add more fields, the single-letter ones always appear on the end.

Example:
```
@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonPropertyOrder({"status", "aName", "code"})
public class MyClass {

  @JsonProperty("aName")
  private String aName;

  @JsonProperty("status")
  private boolean status;

  @JsonProperty("code")
  private Integer code;
}
```

Results in `true,test,25,test` if ran with `new MyClass("test", true, 25)`. It seems like the POJO gets serialized "correctly" and then the single-letter fields get appended again.

What is going on here?

**Comment by cowtowncoder** [comment]
I can't say for sure since it looks like something else (Lombok?) is being used.
But my guess is that Lombok (etc) is creating getter/setter that infers different name -- however, existing of `@JsonProperty` should solve the issue.

What would be needed is actual class definition after post-processing by framework: that would show what is going on.

**Comment by alturkovic** [comment]
It seems like Lombok is generating accesors like this: 

```
public String getAName() {
    return this.aName;
}

public void setAName(String aName) {
    this.aName = aName;
}
```

But Jackson expects a different formatting:
```
public String getaName() {
    return this.aName;
}

public void setaName(String aName) {
    this.aName = aName;
}
```

Which seems pretty odd to me? I guess that the reason that these fields get added in the end is because the mapper adds all unknown fields at the end? So it doesn't recognize them because of different naming convention so it adds it at the end? Pretty weird behavior that might be tricky to debug IMO.

**Comment by cowtowncoder** [comment]
Problem is fundamentally that Bean name transformation can not be fully symmetric for all possible names, and is defined to start from method (getter/setter). Reverse direction (from field to method) is problematic.

So. Whereas Lombok starts with field name, trying to make getter/setter name that matches, Jackson starts with getter/setter name, `getAName()`.
I think that according to regular Bean naming, inferred name would be `AName`, and this is what Jackson would consider name to be when `MapperFeature.USE_STD_BEAN_NAMING` is enable. But with default settings, name would be considered to be `aname`, I think.
Regardless it will not be `aName` no matter what.
So you are right that accessors (field, getter, setter) would not match simply by name.

But when using annotations, annotated names are used for additional linking: it's just that in your case you are just repeating field's name as property name: that won't help with mismatched linking.
If same annotations were added to getter and/or setter, it would actually link however, as it's then match field name.

I think this problem has now been reported a few times but the only way to make things click would be to change Jackson's property introspection to do case-insensitive matching (and even then it would not help with "snake-case" with underscores, or "kebab-case" with hyphens). That is a theoretical possibility for 3.0, if and when that part of codebase needs to be rewritten to solve other issues (mostly to do with Creator introspection), but won't help with 2.x.

Until then I would personally avoid field names that start with single leading lower case character or capital-case, or figure out how to configure Lombok to generate different setter/getter name, or maybe have a way to associate annotation with getter/setter it generates.

**Comment by alturkovic** [comment]
Thank you for the exhaustive explanation!

**Comment by cowtowncoder** [comment]
@alturkovic no problem. I wish I had better solution to offer, but maybe this helps work around the issue.
