### ISSUE TITLE
Empty String deserialized as `null` instead of empty string

### ISSUE THREAD

**Issue by iulianrosca** [FasterXML/jackson-dataformats-text#130]
Hello,

I have the following issue/question for which I was hoping to find a easy solution.

I have inherited a large codebase where I am trying to migrate from jackson 2.6.4 to 2.9.8. The project contains multiple `YAML` files which are deserialized using `com.fasterxml.jackson.dataformat.yaml.YAMLMapper`. Most of these files contain empty fields e.g.
```
emptyStringField:
```
With version 2.6.4 these fields were being decoded to empty strings, while after migrating to 2.9.8 the field evaluated to `null`. I have managed to trace the diverging behavior in `com.fasterxml.jackson.dataformat.yaml.YAMLParser#_decodeScalar`. 
The [2.6 version](https://github.com/FasterXML/jackson-dataformat-yaml/blob/1551c6bd84c65090f5c526492b688a8623612633/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLParser.java#L434) was evaluating the field to `JsonToken.VALUE_STRING` while the [2.9 version](https://github.com/FasterXML/jackson-dataformats-text/blob/f0084060c5b0db6bd7594cc2ac7b481079c79d10/yaml/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLParser.java#L407) is using SnakeYaml implicit resolvers and evaluates to `JsonToken.VALUE_NULL`.

What is the desirable way to keep the behavior from 2.6, deserialize empty fields to empty string instead of null, after migrating to 2.9?

**Comment by cowtowncoder** [comment]
Hmmh. I do not have a good answer here, but "Null replacement/error/skipping" introduced in 2.9:

https://medium.com/@cowtowncoder/jackson-2-9-features-b2a19029e9ff

would at least allow coercing `null` into "" in general. It can be enabled for `String` valued fields, or specific fields.

**Comment by stefanleh** [comment]
Please also check ... https://github.com/FasterXML/jackson-dataformats-text/issues/116

**Comment by cowtowncoder** [comment]
Finally got around to have another look: fix seems easy, but timing is bit challenging as we are past last RC for 2.12.0. I think, however, that I can add a `YAMLParser.Feature`, defaulting to `false` (for 2.12) to allow restoring behavior.

**Comment by cowtowncoder** [comment]
Fixed this by adding a new feature, `YAMLParser.Feature.EMPTY_STRING_AS_NULL`, which defaults to `true` for backwards-compatibility with Jackson 2.11.
It can be disabled to prevent coercion from empty String into `null` in 2.12; we may consider changing default behavior in a later 2.x version as well as 3.0.
