### ISSUE TITLE
`CSVParserBootstrapper` creates `UTF8Reader` which is incorrectly not auto-closed

### ISSUE THREAD

**Issue by iuliu-b** [FasterXML/jackson-dataformats-text#134]
[This line](https://github.com/FasterXML/jackson-dataformats-text/blob/d40f90c4236b8da1f3f52dd55f279ed8a2aab6f4/csv/src/main/java/com/fasterxml/jackson/dataformat/csv/impl/CsvParserBootstrapper.java#L190) creates a UTF8Reader whose autoclose is determined by `_context.isResourceManaged()` alone. In other instances autoclose is determined by `_ioContext.isResourceManaged() || isEnabled(StreamReadFeature.AUTO_CLOSE_SOURCE)` or equivalent (see [YAMLParser](https://github.com/FasterXML/jackson-dataformats-text/blob/d40f90c4236b8da1f3f52dd55f279ed8a2aab6f4/yaml/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLParser.java#L217)).

This means that in cases where `AUTO_CLOSE_SOURCE` is enabled but `isResourceManaged()` is false, files are left open where the user expects them to be auto-closed in line with other class behaviors.

**Comment by cowtowncoder** [comment]
Thank you for reporting this -- yes, sounds like a bug to fix.

**Comment by cowtowncoder** [comment]
Fixed, will be included in 2.10.0.
