### ISSUE TITLE
all and recommended ways to handle: com.fasterxml.jackson.dataformat.csv.CsvMappingException: CSV generator does not support Object values for properties (nested Objects)

### ISSUE THREAD

**Issue by sreev** [FasterXML/jackson-dataformats-text#135]
What are all and recommended ways to handle:
com.fasterxml.jackson.dataformat.csv.CsvMappingException: CSV generator does not support Object values for properties (nested Objects)

Especially, when flow is:
jsonString -> (ObjectMapper) -> JsonNode -> (CsvMapper) -> csvString

**Comment by cowtowncoder** [comment]
Please use mailing list for questions in future.

Short answer is that you will probably need to use `@JsonUnwrapped` to indicate how to "flatten" values of nested POJOs.
