### ISSUE TITLE
Support for Map<String, String> in `JavaPropsMapper`

### ISSUE THREAD

**Issue by filiphr** [FasterXML/jackson-dataformats-text#139]
Currently the `JavaPropsMapper` can only work with `java.util.Properties`. It would be good if there is support for using `Map<String, String>` in addition to `java.util.Properties`.

Would you be open in accepting a PR that adds this support?

**Comment by cowtowncoder** [comment]
I am not sure I understand: `Map`s are supported as values same as with any `ObjectMapper`.
`JavaPropsMapper` only adds couple of convenience methods for specific case of `Properties`.

**Comment by filiphr** [comment]
What I meant is that if you have:

```
Properties properties = new Properties();
properties.put("test.key", "Value");

JsonNode jsonNode = new JavaPropsMapper().readPropertiesAs(properties, JsonNode.class);
System.out.println(jsonNode);
```

you will get

```
{
  "test": {
    "key": "Value"
  }
}
```

However, for `Map<String, String>` you can't. I tried using `convertValue` but that would lead to

```
{
  "test.key": "Value"
}
```

Maybe I should have been more specific. I would like to convert `Map<String, String>` into `JsonNode`. And it seems that this is not possible (or at least I don't know how to do it).

**Comment by cowtowncoder** [comment]
Ah. I think I understand -- so, to convert from Map where keys have dotted notation into logical structure represented? That makes sense.

Technically should be easy, just need to figure out API: could be `readMapAs(...)` I suppose, as changing signature of existing method would be risky for transitive dependencies (even if it could be source compatible as `Properties` implements `Map`).

**Comment by filiphr** [comment]
>Ah. I think I understand -- so, to convert from Map where keys have dotted notation into logical structure represented? That makes sense.

Exactly that. 

`Properties` in the end is a `Map`. However, I do agree with you, new method `readMapAs(...)` will work. My initial idea was to have a new method for it.

**Comment by cowtowncoder** [comment]
Ok cool. I added this on:

https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress

and hope to get this in 2.10.0.pr2 (and final 2.10.0) if all goes well.

**Comment by filiphr** [comment]
That's awesome. Thank you very much. If you need some help let me know
