### ISSUE TITLE
Some enumerated values are mistakenly detected as Booleans

### ISSUE THREAD

**Issue by rburdo** [FasterXML/jackson-dataformats-text#145]
If the yaml file contains an enumerated value like ON or yes, it is detected by the parser as a Boolean constant _true_, rather than an enumerated value.
The code is at com.fasterxml.jackson.dataformat.yaml:YAMLParser class, method is _matchYAMLBoolean.
There should be a way to override this Boolean detection, so such enumerated values are parsed correctly.

**Comment by cowtowncoder** [comment]
I would need bit more information:

1. Which Jackson yaml module version is this with?
2. How are you reading content? (ideally, unit test) -- what is the target Java value.

**Comment by rburdo** [comment]
import io.swagger.v3.parser.OpenAPIV3Parser;
import io.swagger.v3.parser.core.models.SwaggerParseResult;
...
OpenAPIV3Parser parser = new OpenAPIV3Parser();
SwaggerParseResult parseResult = parser.readContents(openApiContent);

I am using swagger-parser 2.0.8 and jackson-dataformat-yaml 2.9.8 .

**Comment by cowtowncoder** [comment]
Unfortunately this is not quit enough: what I mean is exact POJO that content is being read as.
This is needed to know target type, and then it will be possible to figure out what causes coercion.
YAML is very flexible (bit too much for my taste but YMMV) and "ON" happens to be legal Boolean value:

    https://yaml.org/type/bool.html

and so depending on various things, it may be expected that `ON` without quoting is taken as boolean `true` value.

To prevent this values like `ON` actually should be quoted (`"ON"'). But at the same time, if target type is specified as `Enum` it would be nice to be able to prevent coercion. I can't say if that is feasible without knowing all the details.

**Comment by cowtowncoder** [comment]
At this point a full reproduction (unit test needed); may be reopened with one.
