### ISSUE TITLE
Jackson can't handle underscores in numbers

### ISSUE THREAD

**Issue by smedelyan** [FasterXML/jackson-dataformats-text#146]
Not sure I've chosen the right repository to report the issue, but there's a similar one: #65 

I can't see a "dataformats-text" explicit dependency so here's how I use it:

```gradle
compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.9'
compile 'com.fasterxml.jackson.core:jackson-databind:2.9.9.3'
```

Below are tests proving it fails to parse numbers with underscores.

```java
    private static class LongHolder {
        private Long v;

        public Long getV() {
            return v;
        }

        public void setV(Long v) {
            this.v = v;
        }
    }

    private static class IntHolder {
        private Integer v;

        public Integer getV() {
            return v;
        }

        public void setV(Integer v) {
            this.v = v;
        }
    }

    @Test
    public void testYamlUnderscores() throws IOException {
        ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
        mapper.readValue("v: 1000000", IntHolder.class); // ok
        mapper.readValue("v: 1_000_000", IntHolder.class); // ok
        mapper.readValue("v: 1000000", LongHolder.class); // ok

        // throws: com.fasterxml.jackson.databind.JsonMappingException: For input string: "1_000_000"
        mapper.readValue("v: 1_000_000", LongHolder.class);
    }

    @Test
    public void testJsonUnderscores() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.readValue("{\"v\": \"1000000\"}", IntHolder.class); // ok

        // throws:
        // com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java
        // .lang.Integer` from String "1_000_000": not a valid Integer value
        // at [Source: (String)"{"v": "1_000_000"}"; line: 1, column: 7]
        mapper.readValue("{\"v\": \"1_000_000\"}", IntHolder.class);

        mapper.readValue("{\"v\": \"1000000\"}", LongHolder.class); // ok

        // throws:
        // com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java
        // .lang.Long` from String "1_000_000": not a valid Long value
        // at [Source: (String)"{"v": "1_000_000"}"; line: 1, column: 7]
        mapper.readValue("{\"v\": \"1_000_000\"}", LongHolder.class);
    }
```

**Comment by cowtowncoder** [comment]
Yes, this is correct place: thank you reporting the issue!

**Comment by cowtowncoder** [comment]
Adding label `easy` in hopes of getting new contributors to help.

**Comment by chennakesava** [comment]
@cowtowncoder  can you assign this to me?

**Comment by cowtowncoder** [comment]
@chennakesava Done!

**Comment by cowtowncoder** [comment]
One more note: if possible, it'd be great to make the change against `2.10` branch: but I can cherry-pick from `master` too (backport into 2.10). The reason `2.10` is important is that this allows releasing fix quicker (as next patch will be 2.10.1, which will be out sooner than 2.11.0 minor release).

**Comment by conor-ward** [comment]
Hi,
Just wondering if this issue will be fixed in the next release of `jackson-dataformats-text`. Currently have the same issue and wondering if it will be fixed.

Thanks

**Comment by cowtowncoder** [comment]
@conor-ward I don't know if @chennakesava is working on this, but as you can see there is no work linking to this issue yet so nothing committed so far.

**Comment by conor-ward** [comment]
Thanks @cowtowncoder. I believe I have a fix for the issue in YamlParser on the `2.10` branch which passes the `testYamlUnderscores` test above. Do I need to be assigned to an issue in order to be able to add code to the repo?

**Comment by cowtowncoder** [comment]
@conor-ward No, doing a Pull Request is the usual way, but I will assign it to you just as marker for others.

**Comment by cowtowncoder** [comment]
Fixed for 2.10.5, but looks like `snakeyaml-engine` (to be used for 3.0) does NOT recognize underscores on numbers, for some reason.

@asomov I wonder if you know whether YAML 1.2 handling makes this:

```
v: 1_000_000
```

be tagged as String value; `org.snakeyaml` tags it as int.

**Comment by cowtowncoder** [comment]
Looks like this might be change between YAML 1.1 and 1.2:

https://github.com/symfony/symfony/issues/27120

if so, could remove some code from 3.0 as well...

**Comment by conor-ward** [comment]
> Fixed for 2.10.5, but looks like `snakeyaml-engine` (to be used for 3.0) does NOT recognize underscores on numbers, for some reason.
> 
> @asomov I wonder if you know whether YAML 1.2 handling makes this:
> 
> ```
> v: 1_000_000
> ```
> 
> be tagged as String value; `org.snakeyaml` tags it as int.

Thanks for the help @cowtowncoder, just wondering when `2.10.5` is likely to be released?

**Comment by asomov** [comment]
YAML 1.2 is closer to JSON and _ is not a number. But there is a usecase where underscore can be accepted inside integers.
Why would we need it ? Would it lead to confusion ? (JSON does not have it)

**Comment by cowtowncoder** [comment]
@asomov I am not arguing for keeping it (although I can see both some pros and some cons), but mostly wondering about compatibility part, documentation. While Jackson could, if need be, add optional extra coercions, I think I would prefer sticking to default specification defined behavior.

**Comment by asomov** [comment]
YAML 1.2 has added confusion. They introduced schemas. The JSON schema does not accept underscore, and the other schema does. SnakeYAML Engine now only supports JSON schema

**Comment by cowtowncoder** [comment]
Ah. Interesting, did not know this was the main reason.

**Comment by cowtowncoder** [comment]
After implementing #133, underscores are actually handled as expected with upcoming Jackson 2.12.
Handling for Jackson 3.x is bit of an open question, but for 2.x issue is resolved (as "old" snakeyaml does tag such integers as expected and now Jackson decodes them ok too).
