### ISSUE TITLE
jackson-dataformat-yaml unavailable from 2.10 jackson-bom

### ISSUE THREAD

**Issue by sjoerdtalsma** [FasterXML/jackson-dataformats-text#147]
Dependency 

```xml
<dependency>
  <groupId>com.fasterxml.jackson.dataformat</groupId>
  <artifactId>jackson-dataformat-yaml</artifactId>
</dependency>
```

Is declared as version `2.10.0` in [jackson-bom-2.10.0.pom](http://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.10.0/jackson-bom-2.10.0.pom) which cannot be downloaded from maven-central.

For an example where this breaks, please see https://github.com/talsma-ict/enumerables/pull/150

**Comment by cowtowncoder** [comment]
During release processing this occurs as transient condition. I can not think if a way to avoid it, given the way `jackson-bom` and other repos are structured.
To compound the issue, Sonatype OSSRH has been very unreliable, making the end-to-end release span almost 24 hours.

Artifact has now been released however.

**Comment by sjoerdtalsma** [comment]
@cowtowncoder Thank you for the explanation 👍
