### ISSUE TITLE
(yaml) Alias to subtype name

### ISSUE THREAD

**Issue by lburgazzoli** [FasterXML/jackson-dataformats-text#149]
Assuming I have a class like this:

```java
class MyData {
    @JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.WRAPPER_OBJECT)
    @JsonSubTypes({
        @JsonSubTypes.Type(value=SimpleExpression.class, name="simple"),
        @JsonSubTypes.Type(value=GroovyExpression.class, name="groovy")
    })
    public ExpressionDefinition expression
}
```

Is it possible to get the `expression` field automatically aliased as one of the sub types ?

That would allow to deserialize something like:

```yaml
MyData:
  simple: "..."
```

Instead of 

```yaml
MyData:
  expression:
    simple: "..."
```

**Comment by cowtowncoder** [comment]
This might be possible by using `include` of `As.PROPERTY` but also specifying `defaultImpl = TYPE_TO_USE_IF_NO_TYPE_ID_FOUND`

If so, code would try to find type id (from optional `property` annotation property), but if none found, would use whatever class is defined as `defaultImpl`.

**Comment by lburgazzoli** [comment]
That would make the yaml source like:

```yaml
MyData:
  expression:
    type: "simple"
```

Right ?

**Comment by cowtowncoder** [comment]
Actually, I did not notice use of "JsonTypeInfo.As.WRAPPER_OBJECT" -- with that, I don't think you can make it work easily without something like custom deserializer. Problem here is that structure is different and Polymorphic Type handling is expected to either be used for all values, or for none; not on case-by-case basis.

So this is not a supported use case. `defaultImpl` does work with `As.PROPERTY` (and `As.EXISTING_PROPERTY`) but for `WRAPPER_xxx` cases it can only support "unknown" type ids (like say empty String), not changes in content structure.

**Comment by cowtowncoder** [comment]
I don't have any specific idea how I'd go about it, but often it is useful to read all contents as `JsonNode` in deserializer, have a look at what was matched, then delegate with lookups using `DeserializationContext`.

**Comment by lburgazzoli** [comment]
it this something that could be supported out of the box in the future ?

**Comment by cowtowncoder** [comment]
I do not think this is something I would want to add: it seems to me that this would be difficult to implement reliably.
