### ISSUE TITLE
(csv) Add a `CsvParser.Feature.SKIP_EMPTY_LINES` to allow skipping empty rows

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#15]
Looks like a commonly supported option with CSV (family of formats) is to allow skipping of empty rows; that is, ones that only contain white-space.

**Comment by cowtowncoder** [comment]
note: Original had 5 thumbs-up, couple of +1s. So highly requested.

**Comment by kg29** [comment]
Is anyone working on this? I would be happy to pick it up.

**Comment by cowtowncoder** [comment]
@kg29 No one is workign on this as far as I know, so help would be highly valued!

**Comment by kunickiaj** [comment]
This is the only thing preventing us from switching from commons-csv.

**Comment by cowtowncoder** [comment]
@kunickiaj One thing that could help (I may have time to look into this after completing non-blocking json parser) would be a failing unit test that simply shows how you'd like this to work. That is, test that would pass after fix.

**Comment by kunickiaj** [comment]
Yeah, I may look into this once I get a free moment.

We did some benchmarks against jackson csv + guard clause on our side vs commons-csv and it pretty much wiped out any performance gains from moving to jackson.

Figure fixing it here should be a much better option.

**Comment by kunickiaj** [comment]
Here's a trivial test which would pass given the desired behavior.

https://github.com/kunickiaj/jackson-dataformats-text/commit/b34aa58b5cb0a6926485d70fc17d2bc296eac925

**Comment by cowtowncoder** [comment]
Excellent thank you; I'll have a look.

**Comment by cowtowncoder** [comment]
Quick note: I think this makes more sense as `CsvParser.Feature` than `CsvSchema` setting since it's not as much a property of document than handling (although I can see why someone might argue otherwise too). But I think this is more convenient from user perspective.

**Comment by cowtowncoder** [comment]
Hmmh. Looking at code, this may not be easy to implement. As things are, `START_OBJECT` (or, without schema, `START_ARRAY`) is returned without looking at line. Logic would need to check for this setting, then do look-ahead... maybe that works.

**Comment by cowtowncoder** [comment]
For documentation purposes, I'll note that feature itself was actually added in 2.9, but implementation not. This is unfortunate.

**Comment by ehills** [comment]
Hi @cowtowncoder how did this go? Has this been implemented. Your last comment was a wee bit confusing.
Cheers,
Ed

**Comment by cowtowncoder** [comment]
@ehills No, functionality has not been added and does not exist.

**Comment by feirorum** [comment]
Maybe I misunderstand something here, but from the description in the first comment, I think this should be described as "skip blank lines", i.e. lines with only whitespace. Maybe you'd like to add SKIP_BLANK_LINES instead of changing SKIP_EMPTY_LINES to do this, otherwise code which uses the library could change its behaviour when using the new version.

Also, in the linked unit test I don't find any blank (only whitespace) lines, just empty lines:

Current CSV string: 
final String CSV = "1,\"xyz\"\n\ntrue,\n";

Test for blank line being removed would need something like:
final String CSV = "1,\"xyz\"\n\ntrue,\n \n";

The rest of the test would be identical.

Cheers, Anders

**Comment by jabengozartc** [comment]
Not works for me

**Comment by cowtowncoder** [comment]
Good point on "skip blank" vs "skip empty".

**Comment by cowtowncoder** [comment]
And there was much rejoining for now @vboulaye's patch is merges into `2.10`, and the feature shall be supported in patch release 2.10.1!
