### ISSUE TITLE
`YAMLParser._locationFor()` does not use index available from `Mark` object of Event

### ISSUE THREAD

**Issue by robtimus** [FasterXML/jackson-dataformats-text#151]
`YAMLParser._locationFor` [uses -1 for the `totalChars` parameter](https://github.com/FasterXML/jackson-dataformats-text/blob/770ef8403c2e672789fb5dcef66fd066f6432ebb/yaml/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLParser.java#L270) when creating a new `JsonLocation`. However, it has an `index` property which can be used just perfectly for the `totalChars` parameter.

**Comment by cowtowncoder** [comment]
Quick question: what has `index`? Event object parser gets from `SnakeYAML`?

**Comment by robtimus** [comment]
Sorry, I should have been clearer. The `Mark m` object on line 268 has property `index` with method `getIndex()` that can (and probably should) be used instead of the -1.

**Comment by cowtowncoder** [comment]
Ok thanks! I hope to eventually look into this, or, even better case, someone else could have a stab: will label appropriately.
