### ISSUE TITLE
Feature.MINIMIZE_QUOTES must quote strings with YAML boolean values

### ISSUE THREAD

**Issue by erikgb** [FasterXML/jackson-dataformats-text#152]
The [boolean type in YAML](https://yaml.org/type/bool.html) is a bit "special". ;-)

We are facing an issue in f-m-p: https://github.com/fabric8io/fabric8-maven-plugin/issues/1714
The issue was "fixed" temporarily by disabling the MINIMIZE_QUOTES feature when writing YAML-files. Of course this makes the written YAML-files a lot less readable, so we would really like to re-enable the feature.

I have looked a bit closer at this, and it seems like the MINIMIZE_QUOTES feature must handle strings with YAML boolean values a bit more delicately. So I created a project with a test that I expect to pass, and currently it isn't. Please have a look and let me know what you think.
https://github.com/erikgb/boolean-yaml-issue/blob/master/src/test/java/no/boye/YamlBooleanIssueTest.java

**Comment by erikgb** [comment]
This issue seems to have been fixed in the latest version (2.10.0).
Closing issue, and sorry for mixing up the versions....

**Comment by cowtowncoder** [comment]
@erikgb No problem, this is... tricky area. And 2.10.0 is right out of the oven. Glad the fix worked!
