### ISSUE TITLE
Object class type (NATIVE_TYPE_ID??) doesn't do anything

### ISSUE THREAD

**Issue by wiegleyj** [FasterXML/jackson-dataformats-text#160]
I'm using polymorphic types in a project with Lists. (Different objects on the list extended from the same base class). I need this information retained when deserializing. YAML has the ability to include object types. But the Jackson databind for YAML doesn't seem to include this information.

Here's some example code and output. You can see that SnakeYAML does the right thing. Jackson fails to worry about types.

What have I done wrong?

```package com.cyte.mavenproject7;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;
import com.fasterxml.jackson.dataformat.yaml.YAMLParser;
import org.yaml.snakeyaml.Yaml;

public class Example {

    public static class Inner {
        public boolean logic;
        
        public Inner(boolean b) {
            logic = b;
        }
    }

    public static class Extended extends Inner {
        public double dub;
    
        public Extended(boolean b, double d) {
            super(b);
            dub = d;
        }
    }

    public String name;
    public Inner inner;
    public Inner basic;

    public static void main(String [] args) throws JsonProcessingException {
        Example test = new Example();
        test.name = "Jeff";
        test.inner = new Extended(true, 67.8);
        test.basic = new Inner(false);
        
        // Create an ObjectMapper mapper for YAML
        YAMLFactory factory = new YAMLFactory();
        factory.enable(YAMLGenerator.Feature.USE_NATIVE_TYPE_ID);
        ObjectMapper mapper = new ObjectMapper(factory);
        
        for (YAMLParser.Feature c : YAMLParser.Feature.values())
            System.out.println(c);
            
        System.out.println("######Jackson");
        System.out.println(mapper.writeValueAsString(test));
        
        System.out.println("######snakeYAML");
        Yaml yaml = new Yaml();
        System.out.println(yaml.dump(test));
    }
}```

The output is:
```
--- exec-maven-plugin:1.5.0:exec (default-cli) @ mavenproject7 ---
######Jackson
---
name: "Jeff"
inner:
  logic: true
  dub: 67.8
basic:
  logic: false

######snakeYAML
!!com.cyte.mavenproject7.Example
basic: {logic: false}
inner: !!com.cyte.mavenproject7.Example$Extended {dub: 67.8, logic: true}
name: Jeff
```

**Comment by cowtowncoder** [comment]
Which Jackson version is this with?

**Comment by wiegleyj** [comment]
2.10.0

**Comment by cowtowncoder** [comment]
Jackson will only add Type Id when polymorphic handling is enabled: this is typically done by adding `@JsonTypeInfo` either on base class (to be used for all properties of that type), or on property itself.

So in this case, should add `@JsonTypeInfo` on `Inner` declaration.
