### ISSUE TITLE
Update release notes for 2.10.1?

### ISSUE THREAD

**Issue by jimmywan** [FasterXML/jackson-dataformats-text#161]
2.10.1 seems to be released as it's available on maven central and is tagged as a release in GH.

**Comment by cowtowncoder** [comment]
Yes it was released. So what specific change/update are you looking for?

**Comment by jimmywan** [comment]
Nothing other than the release notes still say unreleased. Just wanted to confirm that it's something appropriate for end user consumption and really am accident, per se.

Thanks!

**Comment by cowtowncoder** [comment]
@jimmywan What I meant is... where? There's the release note page:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10.1

where release was mentioned.

**Comment by jimmywan** [comment]
Ahh, I usually look under releases where there was no description.
https://github.com/FasterXML/jackson-dataformats-text/releases/tag/jackson-dataformats-text-2.10.1

So I poked around looking for a changelog and found this.

https://github.com/FasterXML/jackson-dataformats-text/blob/c5e474cea714fa4dbc60c2e0c959a497949129fc/release-notes/VERSION-2.x#L17

**Comment by cowtowncoder** [comment]
Ah. I had forgotten to merge to `master`: change to release notes was done in 2.10 branch.
That makes more sense. Thanks!
