### ISSUE TITLE
`SequenceWriter` does not create multiple docs in a single yaml file

### ISSUE THREAD

**Issue by piyushkumar13** [FasterXML/jackson-dataformats-text#163]
Hi, 
  I am trying to use `SequenceWriter` as suggested [here](https://github.com/FasterXML/jackson-dataformats-text/issues/66#issuecomment-503191465) to serial objects to multidocs but unsuccessful in doing do. Here is my code :
```
File directory = new File("src/main/resources/output");
        String fileName = "output-multidocs.yaml";

        try(SequenceWriter sequenceWriter = mapper.writer().writeValues(new File(directory, fileName))){
            sequenceWriter.init(true);
            sequenceWriter.writeAll(detailsList); // detailsList is an arrayList of object. 
            sequenceWriter.writeAll(detailsList); // Expectation is this would create separate doc in the same yaml file. But it was appending to above list.

        }catch (Exception e){
            e.printStackTrace();
        }
```
Could you please advice me the way to serialize objects into multidocs in a single yaml file.

**Comment by dcoraboeuf** [comment]
Can you put the stack trace you get?

**Comment by piyushkumar13** [comment]
@dcoraboeuf There are no stacktraces since the above code is not throwing any exception. Its working but the second `sequenceWriter.writeAll(detailsList);` is appending detailsList abject in a file instead of creating new doc.

**Comment by cowtowncoder** [comment]
This is odd. When I try to recreate the problem, I actually get an exception (with 2.10.1).
Perhaps this is since I am trying to write main-level POJOs. Will see if array makes a difference.

But at any rate I think things are not working, even if there are different failure modes.

**Comment by piyushkumar13** [comment]
@cowtowncoder I am also using `2.10.1`. You can try using `sequenceWriter.init(true);`. Exception might resolve, since I was also getting some exception without this.

**Comment by cowtowncoder** [comment]
`init()` is not meant to be called by anything other than `ObjectWriter`... I'll add Javadoc stating that. So that should not be work around.

But I think the real problem is that `YAMLGenerator.close()` emits both `DocumentEnd` and `StreamEnd` events (or perhaps that `DocumentEnd` is NOT called at close of root-level Object or Array?).

**Comment by sishbi** [comment]
Hi @cowtowncoder, Do you have an ETA for when 2.10.2 will be released?
I only just came across this issue and saw this thread which indicates that the issue is now resolved!

**Comment by cowtowncoder** [comment]
@sishbi I think it should be released before end of the year, depending on when I have time to cut full minor release. So probably in 2 weeks or so.
