### ISSUE TITLE
Decoding GBK Problem

### ISSUE THREAD

**Issue by wangchengxin** [FasterXML/jackson-dataformats-text#164]
Whether Jackson CSV supports other encodings (except UTF-8)？if have,how to set up,Thank you!

**Comment by cowtowncoder** [comment]
Jackson supports all encodings JSON specification allows: UTF-8, UTF-16 and UTF-32.

If you have to handle content that uses other encodings -- which are not valid JSON, as per original JSON specification -- you will need to create `java.io.Reader` with encoding, and pass that as input source (and similarly, `java.io.Writer` for output).

**Comment by wangchengxin** [comment]
OK, I'll try,thank you!
