### ISSUE TITLE
(yaml) NewLine character is escaped even if LITERAL_BLOCK_STYLE is enabled

### ISSUE THREAD

**Issue by islandshinji** [FasterXML/jackson-dataformats-text#172]
Enable LITERAL_BLOCK_STYLE, but newLine character is escaped in output result.
I confirmed that newLine character is escaped when value include:
* tab character
* trailing space

Is this a normal behavior?

**Comment by cowtowncoder** [comment]
To be honest, I don't know. But details of escaping are handled by SnakeYAML, so I think that as long as expected style is passed, Jackson does not have much control. Except perhaps by adding configuration settings for SnakeYAML.

So this might be question/issue for SnakeYAML.

**Comment by islandshinji** [comment]
As you said this is a limitation of SnakeYAML.
https://bitbucket.org/asomov/snakeyaml/issues/440/literal-style-dump-trailing-space-prevents#comment-51358827
Thank you so much for the support.

**Comment by cowtowncoder** [comment]
You are welcome!
