### ISSUE TITLE
Negative numbers not serialized correctly

### ISSUE THREAD

**Issue by dpbevin** [FasterXML/jackson-dataformats-text#182]
When initializing a `YamlFactory` as follows, negative numbers are not quoted correctly.

```
YAMLFactory factory = new YAMLFactory();
factory.enable(YAMLGenerator.Feature.MINIMIZE_QUOTES);
factory.enable(YAMLGenerator.Feature.ALWAYS_QUOTE_NUMBERS_AS_STRINGS);
```

Serializing `60` currently results in `"60"`.
Serializing `-14` currently results in `14`.

**Comment by cowtowncoder** [comment]
I would need bit more information: 

1. Jackson version (2.10.3?)
2. Code to reproduce: it may be straight-forward from description, but often there is some small setting that changes things -- so I usually ask for exact reproduction just to reduce round-trips to figure out what is different with test I try

and given that should be easy to figure out.

**Comment by cowtowncoder** [comment]
Ah. Thanks!

**Comment by cowtowncoder** [comment]
@dpbevin Thank you very much for reporting this, contributing fix! Backported in 2.10 so it'll be in 2.10.4 as well as 2.11.0.

**Comment by dpbevin** [comment]
> I would need bit more information:
> 
> 1. Jackson version (2.10.3?)
> 2. Code to reproduce: it may be straight-forward from description, but often there is some small setting that changes things -- so I usually ask for exact reproduction just to reduce round-trips to figure out what is different with test I try
> 
> and given that should be easy to figure out.

Sorry... I should have included this info in the report. I got carried away and went straight to the fix 😜

**Comment by cowtowncoder** [comment]
@dpbevin that's perfectly fine, I should have waited couple of minutes :)
