### ISSUE TITLE
CSV mapper nested field support

### ISSUE THREAD

**Issue by jvmlet** [FasterXML/jackson-dataformats-text#189]
Is the subject supported  ?
Having root object defined like this : 

```java
class Parent{
string name;
Child child;
}

class Child{
string name;
}
```
should produce schema and csv like this :
````
# name,  child.name
rootName, childName
````

Thanks

**Comment by cowtowncoder** [comment]
General `@JsonUnwrapped` should work.

**Comment by jvmlet** [comment]
Thanks. I overlooked the limitation section in readme. In my case @JsonUnwrapped can't be used as the beans are third party objects. What I did is I created Map of string to object values from root object and used writer for Map. Thanks for answering though.

**Comment by cowtowncoder** [comment]
@jvmlet That works -- but you can always use mix-in annotations to apply Jackson annotations over 3rd party types too. Just in case that might be useful for future.

But glad it works for you: use of intermediate `Map` for processing (or `JsonNode`) is a common technique and often a very good choice, flexible, gives full power etc.

**Comment by jvmlet** [comment]
Thanks, I'm aware about mix-ins. I'm not sure it helps me because the columns are dynamic and the hierarchy and nesting levels might be too deep. We are exporting Elastic search data into csv based of user defined reports. Flattering ES mapped POJO  (with spring elasticsearch ) into map works perfectly well for us. Thanks again for your support.

**Comment by cowtowncoder** [comment]
@jvmlet Ah. Ok, yes, makes sense. Just wanted to make sure.
