### ISSUE TITLE
yaml emoji to string 

### ISSUE THREAD

**Issue by jzdayz** [FasterXML/jackson-dataformats-text#190]
a.yaml
```yaml
a:
  b: 😑
```
java code
```java
public class A {
    public static void main(String[] args) throws Exception{

        ObjectMapper objectMapper = new ObjectMapper(new YAMLFactory());

        String s1 = "";
        try (
                InputStream resourceAsStream = A.class.getResourceAsStream("/a.yaml")
                ){
            s1 = StreamUtils.copyToString(resourceAsStream, Charset.defaultCharset());
        }catch (Exception e){
            e.printStackTrace();
        }


        HashMap hashMap = objectMapper.readValue(s1, HashMap.class);

        System.out.println(hashMap);

        Yaml yaml = new Yaml();

        System.out.println(yaml.dump(hashMap));

        System.out.println(objectMapper.writeValueAsString(hashMap));
    }
}
```
console output 
```txt
{a={b=😑}}
a: {b: 😑}

---
a:
  b: "\U0001f611"
```

### question: Hot to display 
```yaml
a:
  b:  😑
```

**Comment by cowtowncoder** [comment]
I am not quite sure what you are asking, but please note that:

    System.out.println()

call is outside control of Jackson and depends on your local system and console/terminal settings. Whether that displays Unicode value or not is quite separate from Jackson handling.
What Jackson can guarantee is encoding and decoding Unicode values correctly, and this can not be verified by printing out Strings.

**Comment by jzdayz** [comment]
> I am not quite sure what you are asking, but please note that:
> 
> ```
> System.out.println()
> ```
> 
> call is outside control of Jackson and depends on your local system and console/terminal settings. Whether that displays Unicode value or not is quite separate from Jackson handling.
> What Jackson can guarantee is encoding and decoding Unicode values correctly, and this can not be verified by printing out Strings.

But snakeyaml can display '😑' ,  Code `objectMapper.writeValueAsString(hashMap) `  change '😑' into "\U0001f611"

**Comment by cowtowncoder** [comment]
Unfortunately I still do  not understand what you are trying to say is the problem.

Test will have to verify actual String contents and NOT print out something to `System.err` or `System.out` (since latter may or may not break encoding).

Test should embed input (and not use external file), and use of this:

```
StreamUtils.copyToString(resourceAsStream, Charset.defaultCharset());
```

is basically wrong: `Charset.defaultCharset` on my system may be different than on your system. So that should probably be "UTF-8", unless content is encoded using something else.

**Comment by jzdayz** [comment]
> Unfortunately I still do not understand what you are trying to say is the problem.
> 
> Test will have to verify actual String contents and NOT print out something to `System.err` or `System.out` (since latter may or may not break encoding).
> 
> Test should embed input (and not use external file), and use of this:
> 
> ```
> StreamUtils.copyToString(resourceAsStream, Charset.defaultCharset());
> ```
> 
> is basically wrong: `Charset.defaultCharset` on my system may be different than on your system. So that should probably be "UTF-8", unless content is encoded using something else.

yes , it's UTF-8 , I just want to display '😑'  and not to \U0001f530 

Before code `objectMapper.writeValueAsString(hashMap)`
![image](https://user-images.githubusercontent.com/35563513/78977733-362e7780-7b4b-11ea-9e54-b4b1365f87a4.png)

After code
![image](https://user-images.githubusercontent.com/35563513/78977986-9d4c2c00-7b4b-11ea-9fab-2c296e7b4de4.png)

I think it should display emoji 

Just like snakeyaml dump
![image](https://user-images.githubusercontent.com/35563513/78978123-d4224200-7b4b-11ea-8012-328b8b11aa0e.png)

This is my modified code
```java
 public static void main(String[] args) throws Exception{

        ObjectMapper objectMapper = new ObjectMapper(new YAMLFactory());

        String s1 = "";
        try (
                InputStream resourceAsStream = A.class.getResourceAsStream("/a.yaml")
                ){
            s1 = StreamUtils.copyToString(resourceAsStream, StandardCharsets.UTF_8);
        }catch (Exception e){
            e.printStackTrace();
        }


        HashMap hashMap = objectMapper.readValue(s1, HashMap.class);

        System.out.println(hashMap);

        Yaml yaml = new Yaml();

        System.out.println(yaml.dump(hashMap));

        System.out.println(objectMapper.writeValueAsString(hashMap));
    }
```

**Comment by cowtowncoder** [comment]
This is not unit test. It does not help to show ACTUAL PROBLEM. Your writing to console with `System.out.println()` proves exactly nothing -- not just because of encoding issues, but because `yaml.dump` and `ObjectMapper.writeValueAsString()` are not necessarily even supposed to return same thing.

At this point I want runnable code like unit test to show the problem, no more descriptions that are of no help.
