### ISSUE TITLE
`ArrayIndexOutOfBoundsException` when skipping empty lines, comments

### ISSUE THREAD

**Issue by f-julian** [FasterXML/jackson-dataformats-text#191]
Hi we found a bug in the csv parsing.

For some csv files parsing fails with:

`java.lang.ArrayIndexOutOfBoundsException: Index 4000 out of bounds for length 4000
	at com.fasterxml.jackson.dataformat.csv.impl.CsvDecoder.skipLinesWhenNeeded(CsvDecoder.java:527)
	at com.fasterxml.jackson.dataformat.csv.impl.CsvDecoder.startNewLine(CsvDecoder.java:499)`

I did some digging it happens if there is a newline as char 4000 in the csv file.

Happens in versions > 2.10.0

I think it was introduced with #15

Can i help with a fix?

**Comment by f-julian** [comment]
added failing testcase to reproduce the probem.

**Comment by cowtowncoder** [comment]
@f-julian thank you for reporting the issue! Will have a look.

**Comment by cowtowncoder** [comment]
Shoot. I really should have spent more time code reviewing that change (plus, should NOT have gone in a patch release). It assumes all content will reside in buffer, which is exactly what Jackson does not do or guarantee.
