### ISSUE TITLE
Not able to create Nested YAML

### ISSUE THREAD

**Issue by jaykeerti** [FasterXML/jackson-dataformats-text#193]
```
---
-
  - apple
  - ball
  - cat

```
I need the above format (Nested Yaml). is it possible?

String [] arr = {"apple","ball","cat"};
 YAMLFactory yamlFactory = new YAMLFactory();
 YAMLMapper mapper = new YAMLMapper(yamlFactory);
yamlFactory.disable(YAMLGenerator.Feature.SPLIT_LINES);
yamlFactory.enable(YAMLGenerator.Feature.LITERAL_BLOCK_STYLE);
mapper.writeValueAsString(arr);

produces:
```
---
- apple
- ball
- cat
```

**Comment by cowtowncoder** [comment]
Being usage question this does not belong to issue tracker but ideally on mailing list:

https://groups.google.com/forum/#!forum/jackson-user

or chat

https://gitter.im/FasterXML/jackson-databind

but as to question: yes, try using nest Java data structure. Lists of lists or arrays of arrays.
