### ISSUE TITLE
CSVColumns are not ordered when using Iterator<ConcurrentHashMap<String, String>>

### ISSUE THREAD

**Issue by nidhin-tm** [FasterXML/jackson-dataformats-text#206]
when I am using  Iterator<ConcurrentHashMap<String, String>>  as a reader than getting column is not like in CSV file. Column and value are aligned, but the order of the column is not the same as in CSV file

`CsvMapper  csvMapper = new CsvMapper();
        csvMapper.enable(CsvParser.Feature.WRAP_AS_ARRAY);
        CsvSchema csvSchema = CsvSchema.builder().build().withColumnSeparator(delimiter.charAt(0)).withHeader();
        Iterator<ConcurrentHashMap<String, String>> iterator = csvMapper.readerFor(ConcurrentHashMap.class)
                .with(csvSchema).readValues(reader);`

**Comment by cowtowncoder** [comment]
I am not sure I understand this issue: my understanding is that `ConcurrentHashMap` entries have arbitrary ordering, similar to `HashMap`. If you want ordering to be the same as read order, shouldn't you use `LinkedHashMap`?
