### ISSUE TITLE
Wiki links broken 

### ISSUE THREAD

**Issue by bhchandra** [FasterXML/jackson-dataformats-text#21]
1. **Wiki** link broken in https://github.com/FasterXML/jackson-dataformats-text/tree/master/csv  
2.  **Wiki** link redirects to the same page in https://github.com/FasterXML/jackson-dataformats-text

**Comment by cowtowncoder** [comment]
Thanks!

**Comment by bhchandra** [comment]
:smiley:

**Comment by cowtowncoder** [comment]
Ok, fixed some of linkage; and copied `CsvSchema` page to the new repo. One challenge is that things need to be reorged due to combination of multiple backend under same repo, wiki (older repos will be eventually rm'ed or at least made private).
