### ISSUE TITLE
CSV: Should quote strings with line separator under STRICT_CHECK_FOR_QUOTING mode

### ISSUE THREAD

**Issue by wkwkhautbois** [FasterXML/jackson-dataformats-text#217]
When string data with line separator is serialized to csv, it shold be quoted, shouldn't it?
But it actually is NOT quoted if `CsvGenerator.Feature.STRICT_CHECK_FOR_QUOTING` is enabled.

Test below is failed:

```java
public void testExplicitWithLineSeparator() throws Exception
{
    CsvSchema schema = CsvSchema.emptySchema();
    ObjectWriter writer =  new CsvMapper().writer(schema)
            .with(CsvGenerator.Feature.STRICT_CHECK_FOR_QUOTING);

    String csv =writer.writeValueAsString(new Object[]{"abc", "de\nf", "ghi"});
    assertEquals("abc,\"de\nf\",ghi\n", csv);  // FAILED!
}
```

```
expected:<abc,["de
f"],ghi
> but was:<abc,[de
f],ghi
>
```

version:  v.2.11.2 and currrent master branch

**Comment by cowtowncoder** [comment]
@wkwkhautbois thank you once again for reporting this issue, contributing the fix. Will be in 2.11.3 / 2.12.0.
