### ISSUE TITLE
CSV: ALLOW_MISSING_VALUES

### ISSUE THREAD

**Issue by bmarcj** [FasterXML/jackson-dataformats-text#218]
The CsvMapper.Builder class:

```
 CsvMapper.builder()
                .addModule(module)
                .enable(JsonParser.Feature.ALLOW_MISSING_VALUES)
               .build()
```

`JsonParser.Feature.ALLOW_MISSING_VALUES` is deprecated, and the replacement is `com.fasterxml.jackson.core.json.JsonReadFeature#ALLOW_MISSING_VALUES`. 

Unfortunately, the builder has no methods to enable `JsonReadFeature` features.

**Comment by cowtowncoder** [comment]
@bmarcj This underlines the fact (previously sort of hidden) that this option did not work with CSV format to begin with -- it was used to allow "JSON" content like

```
[ 1, 2, , 4 ]
```

and as such there is no format-agnostic replacement (`StreamReadFeature`) but rather new feature is specifically JSON-specific (as per name `JsonReadFeature`).
So while existing code may have set/cleared this feature, it would not have done anything for CSV.
New division into features should make this easier to spot.

**Comment by bmarcj** [comment]
Ah, thank you.  That makes sense.
