### ISSUE TITLE
(csv) Invalid CSV file gets serialized as empty List

### ISSUE THREAD

**Issue by sonOfRa** [FasterXML/jackson-dataformats-text#223]
When a schema is configured with a header, and the reader is configured to fail on missing columns,
a header that does not match the type we want to match to, and no actual data, results in an empty list, rather than an exception being thrown.

As always, full demo provided over at https://github.com/sonOfRa/jackson-csv-empty-bug

I'd be happy to provide additional info if needed

**Comment by cowtowncoder** [comment]
@sonOfRa First of all, thank you for reporting the issue, and esp. providing reproduction. Apologies for slow follow-up; I'll have a look.

**Comment by cowtowncoder** [comment]
Hmmh. I am not sure this is a bug, actually.

Looking at the test input, it seems to only have the header line, and no data: one linefeed ends the header row but that's it.
If I add one more linefeed to create an empty data row there is an exception.

So to me this actually seems to behave is intended. You may want to catch the case of no data, if you want?

**Comment by sonOfRa** [comment]
I think it might be reasonable to mark this wontfix, yeah. But the behaviour that surprised us was that if we configure the Schema with FAIL_ON_MISSING_COLUMNS, and the header that is found does not actually match the schema of the Data Type we are reading, an exception occurs only if there actually is any data. On a closer read, FAIL_ON_MISSING_COLUMNS however only *counts* the amount of columns and fails if if there aren't enough, rather than verifying  that they match the schema.

**Comment by cowtowncoder** [comment]
@sonOfRa Another reason this might be surprising is the difference between "values" (data rows) and header entries -- I think you would want to verify header observed and schema defined?
Naming can be seen as bit ambiguous in this case.

But I think there is another setting that might help: `CsvSchema` has "strict headers", usable either:

1. via `CsvSchema.Builder.setStrictHeaders(true)`
2. via `CsvSchema.withStrictHeaders(true)` mutant factory method

I am not 100% sure but I think this setting might be along what you want?

**Comment by sonOfRa** [comment]
I just validated this, and yes, it works!

It requires that we also use the typedSchema variant like so:

```
        CsvSchema bootstrapSchema = mapper.typedSchemaFor(Data.class)
                .withHeader()
                .withArrayElementSeparator(",")
                .withColumnSeparator(';')
                .withEscapeChar('"')
                .withStrictHeaders(true);
        objectReader = mapper.readerFor(Data.class).with(bootstrapSchema);
```
In that case, a JsonParseException is thrown when the header is not using the correct names, or is incorrectly ordered. Thank you!

**Comment by cowtowncoder** [comment]
@sonOfRa Oh. And non-typed one does not... .? That seems odd, I'd think it should be the same for both.

**Comment by sonOfRa** [comment]
I'll try again tomorrow, maybe I just need ```.schemaFor(Data.class)```, but it definitely needs at least one of those. Which seems reasonable, because if I only define the data class in the reader, rather than the schema, and the validation happens at parse-time, rather than mapping-time, I'm going to need to be telling jackson what the headers are at that point.

**Comment by cowtowncoder** [comment]
@sonOfRa Ok: yes, you do need a schema (from POJO or explicitly constructed with Builder). Just wanted to make sure if there were further constraints so my understanding is accurate.
