### ISSUE TITLE
CsvMapper support for JsonView-aware schema generation

### ISSUE THREAD

**Issue by k-brooks** [FasterXML/jackson-dataformats-text#238]
The schema generation process through introspection by the CsvMapper class is very handy, it would be great if we could provide a view in this process to filter out fields which are irrelevant. This is especially important when outputting headers which one would like to be filtered.

**Comment by k-brooks** [comment]
Something as simple as the following would suffice
`  protected void _addSchemaProperties(
      CsvSchema.Builder builder,
      AnnotationIntrospector intr,
      boolean typed,
      JavaType pojoType,
      NameTransformer unwrapper, Class<?> view)
  {
    if (_nonPojoType(pojoType)) {
      return;
    }

    BeanDescription beanDesc = getSerializationConfig().introspect(pojoType);
    for (BeanPropertyDefinition prop : beanDesc.findProperties()) {
      if (!prop.couldSerialize()) {
        continue;
      }
      Class<?>[] viewArray = prop.findViews();
      if (viewArray != null && viewArray.length > 0 && !Arrays.asList(viewArray).contains(view)) {
        continue;
      }
...
`

**Comment by cowtowncoder** [comment]
Hmmh. Interesting. I'll add this on my todo list to investigate for 2.13. And would be happy to get a PR too of course.

**Comment by k-brooks** [comment]
I will start on this now, PR should be up soon

**Comment by k-brooks** [comment]
Looks like this may already exist
https://github.com/FasterXML/jackson-dataformats-text/pull/195

**Comment by k-brooks** [comment]
Confirmed, already supported - sorry for the unnecessary issue

**Comment by cowtowncoder** [comment]
lol. And I should have remembered having helper with the earlier PR :)
