### ISSUE TITLE
YAML serialization do not work

### ISSUE THREAD

**Issue by Zdziszkee** [FasterXML/jackson-dataformats-text#266]
![image](https://user-images.githubusercontent.com/52966846/115166602-40ffde80-a0b4-11eb-9b0b-24e00eddc075.png)
![image](https://user-images.githubusercontent.com/52966846/115166628-668ce800-a0b4-11eb-97d2-bba57ac728e3.png)
![image](https://user-images.githubusercontent.com/52966846/115166636-799fb800-a0b4-11eb-80c2-0228db0c7ad9.png)
![image](https://user-images.githubusercontent.com/52966846/115166952-f2534400-a0b5-11eb-80e9-b191e2f4cad5.png)
![image](https://user-images.githubusercontent.com/52966846/115167086-65f55100-a0b6-11eb-9a55-14d52c825379.png)

Okay so basically, jackson is trying to use not existing method?

**Comment by cowtowncoder** [comment]
@Zdziszkee showing a screenshot does not help anyone to reproduce issue you are seeing -- I am not aware of any such compatibility problems. Two things that would help:

1. Add a reproduction (unit test) with minimal code, not including external frameworks: something that shows exception you see
2. Ensure that you are using a compatible set of versions (use gradle's `dependencyInsight` task I think?)

It seems as if you were overriding `snakeyaml` version for some reason: keep in mind that dataformat module defines version it prefers so you may also try to see if removing the override helps.

**Comment by Zdziszkee** [comment]
Issue was my mistake sorry! (There was older version of snakeyaml in runtime)

**Comment by cowtowncoder** [comment]
@Zdziszkee ok glad you were able to figure out the issue and fix it!
