### ISSUE TITLE
jackson-dataformat-yaml support in 2.12.3

### ISSUE THREAD

**Issue by roimenashe** [FasterXML/jackson-dataformats-text#267]
If I upgrade "jackson-dataformat-yaml" artifact to 2.12.3 in the pom.xml file - 1 external library is missing
"Maven: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.3".
which causes "YAMLFactory" class usages to be missing.

Version 2.12.3 external libraries:
![image](https://user-images.githubusercontent.com/33356310/115199421-dd010880-a0fb-11eb-84fc-2c78a80daa91.png)

Version 2.12.2 external libraries:
![image](https://user-images.githubusercontent.com/33356310/115199113-81cf1600-a0fb-11eb-86ac-9f731055b919.png)

I tried to find information regarding deprecation or replacement but I couldn't find any.

Thanks

**Comment by cowtowncoder** [comment]
Type `YAMLFactory` is definitely included in `jackson-dataformat-yaml` in both 2.12.2 and 2.12.3. But it looks like you only included that jar in second case, not former?
So perhaps you are not included that component somehow?

**Comment by roimenashe** [comment]
I just change the version number under the properties section on the pom.xml file:

...
<properties>
		...
		<jackson-dataformat-yaml.version>2.12.2</jackson-dataformat-yaml.version>
</properties>
...
<dependency>
		    <groupId>com.fasterxml.jackson.dataformat</groupId>
		    <artifactId>jackson-dataformat-yaml</artifactId>
		    <version>${jackson-dataformat-yaml.version}</version>
</dependency>

Every version below 2.12.3 works fine, once I change it to 2.12.3 the last jar out of the four ("Maven: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.3") is missing, I'll try to see if its related to my env (plugins, m2...) but it looks like a bug.

**Comment by roimenashe** [comment]
"3. If all else fails: In Intellij, Select "Invalidate caches/Restart" -> Close Intellij -> Go to the project folder and delete .idea folder -> Reopen Intellij and "mvn clean install"

Found in: https://stackoverflow.com/questions/45442106/intellij-is-not-showing-external-libraries-in-project-tab/67102413#67102413

Fixed the issue, thanks for the help!

**Comment by cowtowncoder** [comment]
Thank you for documenting the steps that worked @roimenashe!
