### ISSUE TITLE
[jackson-dataformat-csv] Should not quote with strict quoting when line starts with #, but comments are disabled

### ISSUE THREAD

**Issue by kdebski85** [FasterXML/jackson-dataformats-text#270]
When STRICT_CHECK_FOR_QUOTING is enabled and withoutComments() is used, Jackson should not escape strings starting with "#"

```
CsvMapper mapper = new CsvMapper();
mapper.configure(CsvGenerator.Feature.ALWAYS_QUOTE_STRINGS, false);
mapper.configure(CsvGenerator.Feature.STRICT_CHECK_FOR_QUOTING, true);

CsvSchema schema = mapper.schemaFor(recordClass).withoutComments();
mapper.writerFor(recordClass).with(schema).writeValue(wrtiter, record);
```

The record contains a single string field with value #abc.

Expected:
#abc is written to CSV file

Actual:
"#abc" is written to CSV file

In CsvEncoder::_needsQuotingStrict "(c == '#' && i == 0)" should be checked only when comments are enabled.

**Comment by kdebski85** [comment]
Additionally, in strict mode '#' should only add quotes if it is used in the first column. When it used in any other column, quotes are not needed.
I created pull request to address that. I will send CLA today.

**Comment by yawkat** [comment]
fyi, tatu is away until next week, so you may have to wait a few days.
