### ISSUE TITLE
YAMLGenerator does not quote tilde (~) characters when MINIMIZE_QUOTES is enabled

### ISSUE THREAD

**Issue by jameswynn** [FasterXML/jackson-dataformats-text#274]
As of 2.11.4 YAMLGenerator does not quote the tilde character when MINIMIZE_QUOTES is enabled. The YAML spec states that tilde represents null, and in fact Jackson interprets it as such, but it does not quote strings containing this by default. This should be included in the list of other special characters that get quoted as per #180.

**Comment by cowtowncoder** [comment]
Thank you for reporting this: it sounds like a flaw.
I assume that check for tilde should only consider the first (non-space?) character; or possibly just full value being tilde. Leading white-space may be a challenge however so alternatively could simply check for existence in general I suppose.

PR for quoting would be highly welcome: I hope to get to this eventually (right now I am bit time-limited) but will try my best to help with PRs.

**Comment by cowtowncoder** [comment]
Fixed for 2.12(.4), with a simple test reproduction

Thank you for reporting this @jameswynn!
