### ISSUE TITLE
Support CSV Deserialization to EnumMaps

### ISSUE THREAD

**Issue by matthias-mueller** [FasterXML/jackson-dataformats-text#277]
During the last years I did a lot of CSV reading (with and without Jackson). When parsing this type of data with Jackson, I often serialize rows to maps, when there is some sort of dynamics in the data that is impractical to handle with POJO mappers.

This is a typical example:

```java
CsvSchema headerSchema = CsvSchema.emptySchema().withHeader();
MappingIterator<Map<String, String>> it = mapper
                .readerForMapOf(String.class)
                .with(schema)
                .readValues(input);
while (it.hasNext()) {
  Map<String, String> row = it.nextValue();
  String xVal = row.get("x");
  String yVal = row.get("y");
  String temperature = row.get("temperature");
  // do something with the values
  ...
}
```

The usual situation is that all the valid header values stem from a fixed set of strings, so there is an immediate association with Java Enums. I would like to do something like this:

```java
enum MyEnum {
  X, Y, TEMPERATURE, HUMIDITY, ... ;
}

static MyEnum parse(String s) {
  ... // a separate method or an implementation detail of the enum class
}

...

CsvSchema headerSchema = CsvSchema.emptySchema().withHeader();
MappingIterator<EnumMap<MyEnum, String>> it = mapper
                .readerForMapOf(MyEnum.class, h -> parse(h), String) // specify enum type, mapping function header->enum, value class
                .with(schema)
                .readValues(input);
while (it.hasNext()) {
  EnumMap<MyEnum, String> row = it.nextValue();
  String xVal = row.get(X);
  String yVal = row.get(Y);
  String temperature = row.get(TEMPERATURE);
  // do something with the values
  ...
}
```
Besides rigour, Enum headers / EnumMaps have other advantages, such as internal optimizations for speed and memory footprint (compared to `HashMap` or `LinkedHashMap`).

Would that proposal be something that is within the scope of this library?

**Comment by cowtowncoder** [comment]
Ahh. Yes, I think the general idea (if I understood it right) of allowing column definition as `Enum`s sounds useful, so I would be open for adding such functionality.

I think the immediate challenge would be in figuring out how to make that work through APIs.
General `MappingIterator` is defined and implemented by `jackson-databind`, and `Map` keys (and in general Object property names) are assumed to come as `String`s. So while my first instinct would have been to consider mapping column names to `Enum`s in CSV module (CsvParser maybe), that would be difficult to flow through.

At the same time, transformation on databind side can be challenging.

But maybe it is worth asking this: would it not "just work", if column name itself can be deserialized as target Enum?
There are a few annotations that can be used for this purpose, or if worse comes to worse, a custom `KeyDeserializer` can be specified.

**Comment by matthias-mueller** [comment]
I had somewhat expected that the change would not be trivial. Since you've asked what would "just work" for me, here's a very typical example of what I would like to do enum-wise:

```java
enum HeaderField {
    // define enum values and their corresponding "external" representations.
    ID("identifier"),
    X("x"),
    Y("y"),
    TEMPERATURE("Temp."),
    HUMIDITY("Hum.");
    
    private final String code;
    
    HeaderField(String code) {
        this.code = code;
    }
    
    String code() {
        return code
    }
    
    // convert header field / property name to Enum
    static HeaderField parse(String s) {
        for (HeaderField a : HeaderField.values()){
            if (a.code().equals(s)) {
                return a;
            }
        }
        throw new IllegalArgumentException("Unrecognized field: " + s);
    }

}
``` 
For the mapping part I could probably use any API elements (e.g. `KeyDeserializer`) that Jackson provides als long a I am able to hook `HeaderField#parse()` into it. I am not familiar with Jackson's internals but it would be great, if the String -> Enum mapping is performed only once.
Result-wise I'd really like to leverage the `EnumMap` (at least internally) as a return type because it provides (array-like) efficiency gains compared to the hash-based Map implementations. The JDK also has internal optimizations to deal with very small Enum key sets, which is often the case for CSV files.

Maybe there is a more general way to leverage EnumMaps in Jackson, if the framework sees that a particular `KeyDeserializer` maps Object property names to an Enum? In that case the Jackson APIs might stay unchanged and still return `Map<?,?>`, but there would be am internal code path that creates (probably via reflection) an `EnumMap` return value.

**Comment by cowtowncoder** [comment]
Ok, so what I mean is that would adding of `@JsonCreator` next to `parse` method work -- it should, I think.
And for serialization, `@JsonValue` next to method `code()`.

In fact, I think that use of `@JsonValue` should handle both cases, if external representation is the value that method returns.

This aspect of Enums is not well documented as improvements have been added piece by piece over time.

Finally, also notice that you can use `@JsonProperty` on enum entries: value specified is the external value (one included in JSON) to use, and would override `Enum.name()`.

**Comment by matthias-mueller** [comment]
I can confirm this is working - here's a little test for the record:

```java
public class JacksonCsvTest {

    enum HeaderField {
        // define enum values and their corresponding "external" representations.
        ID("identifier"),
        X("x"),
        Y("y"),
        TEMPERATURE("Temp."),
        HUMIDITY("Hum.");

        private final String code;

        HeaderField(String code) {
            this.code = code;
        }

        @JsonValue
        String code() {
            return code;
        }

    }

    @Test
    public void toEnumMapTest() throws IOException {
        String input = "x,y,Temp.\n12,3,way too hot\n12,3,way too hot\n12,3,way too hot";

        CsvMapper mapper = new CsvMapper();
        CsvSchema schema = CsvSchema.emptySchema().withHeader();
        MapType javaType = mapper.getTypeFactory().constructMapType(EnumMap.class, HeaderField.class, String.class);
        
        MappingIterator<EnumMap<HeaderField, String>> it = mapper
                .readerFor(javaType)
                .with(schema)
                .readValues(input);
        
        while (it.hasNext()) {
            Map<HeaderField, String> row = it.nextValue();
            String xVal = row.get(HeaderField.X);
            String yVal = row.get(HeaderField.Y);
            String temperature = row.get(HeaderField.TEMPERATURE);
            // do something with the values
            assertEquals("12", xVal);
            assertEquals("3", yVal);
            assertEquals("way too hot", temperature);
        }
    }
}
```

I haven't tested performance yet, but have confirmed that `HeaderField#code()` is called exactly 5 times - which corresponds to the number of enum entries.

**Comment by cowtowncoder** [comment]
@matthias-mueller correct, it should call it once per entry, create a lookup map and use that.

**Comment by matthias-mueller** [comment]
Since my original problem is solved, I will close the issue now. Thanks a lot for your help!

**Comment by matthias-mueller** [comment]
So with some flimsy (non-JMH) benchmarking I get these approximate read times:
(The resulting maps' elements are accessed a single time. Data generation and stream reading is _included_ in the following timings and takes about 9 seconds.)

* Map.class (=LinkedHashMap.class) = 19 seconds
* HashMap.class = 18 seconds
* EnumMap.class = 16 seconds

So my first Estimate of the speed gain in the `EnumMap` deserialization would be somewhere between 20..30% compared to "standard" `readerForMapOf` deserialization. Results may vary in other setups.

**Comment by cowtowncoder** [comment]
`EnumMap` has a bit less overhead for storage (since it's typically an `Object[]` indexed by `enum.index()`) so it makes sense I guess. Glad that things work functionally, as expected.

**Comment by matthias-mueller** [comment]
I have one more issue though: If my Enum is incomplete, e.g. the CSV has additional header fields that are not defined in the enum, Jackson throws an exception:

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `de.opensensorweb.harvesting.helpers.csv.JacksonCsvEnumTest$HeaderField` from String "ND": not a valid representation, problem: (com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type `de.opensensorweb.harvesting.helpers.csv.JacksonCsvEnumTest$HeaderField` from String "ND": not one of the values accepted for Enum class: [identifier, Temp., x, y, Hum.]
 at [Source: (StringReader); line: 2, column: 18]

	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdKeyException(DeserializationContext.java:1656)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdKey(DeserializationContext.java:889)
	at com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer.deserializeKey(StdKeyDeserializer.java:138)
	at com.fasterxml.jackson.databind.deser.std.EnumMapDeserializer.deserialize(EnumMapDeserializer.java:278)
	at com.fasterxml.jackson.databind.deser.std.EnumMapDeserializer.deserialize(EnumMapDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.EnumMapDeserializer.deserialize(EnumMapDeserializer.java:24)
	at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:280)
```
I've tried `@JsonIgnoreProperties` and `CsvMapper().disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)` but none of these seems to work:

```java
@JsonIgnoreProperties(ignoreUnknown = true)
    enum HeaderField {
        // define enum values and their corresponding "external" representations.
        ID("identifier"),
        X("x"),
        Y("y"),
        TEMPERATURE("Temp."),
        HUMIDITY("Hum.");

        private final String code;

        HeaderField(String code) {
            this.code = code;
        }

        @JsonValue
        String code() {
            return code;
        }

    }

    // sample size for generated rows
    private static final int GENERATED_ROW_COUNT = 20_000_000;

    /**
     * Serialize CSV to {@link EnumMap}
     */
    @Test
    public void toEnumMapTest() throws IOException {
        String input = "x,y,Temp.,ND\n12,3,way too hot,f\n12,3,way too hot,f\n12,3,way too hot,f";

        ObjectMapper mapper = new CsvMapper().disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        CsvSchema schema = CsvSchema.emptySchema().withHeader();
        MapType javaType = mapper.getTypeFactory().constructMapType(EnumMap.class, HeaderField.class, String.class);

        MappingIterator<EnumMap<HeaderField, String>> it = mapper
                .readerFor(javaType)
                .with(schema)
                .readValues(input);

        while (it.hasNext()) {
            Map<HeaderField, String> row = it.nextValue();
            String xVal = row.get(HeaderField.X);
            String yVal = row.get(HeaderField.Y);
            String temperature = row.get(HeaderField.TEMPERATURE);
            // do something with the values
            assertEquals("12", xVal);
            assertEquals("3", yVal);
            assertEquals("way too hot", temperature);
        }
    }
```

**Comment by cowtowncoder** [comment]
There are couple of possibilities there.

`DeserilizationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL` would often work, but is not valid as `EnumMap` key.

Or you can annotate one of `Enum` values with `@JsonEnumDefaultValue`, which would use that one for anything that does not otherwise map.

And finally I think you should also be able to annotated a factory method of enum class with `@JsonCreator` for fully customized resolution.

**Comment by matthias-mueller** [comment]
Thanks @cowtowncoder - for the record I can confirm that the following code is working (`@JsonEnumDefaultValue` also needs `DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE` enabled):

```java
    enum HeaderField {
        // define enum values and their corresponding "external" representations.
        ID("identifier"),
        X("x"),
        Y("y"),
        TEMPERATURE("Temp."),
        HUMIDITY("Hum."),
        @JsonEnumDefaultValue
        NONE(null);

        private final String code;

        HeaderField(String code) {
            this.code = code;
        }

        @JsonValue
        String code() {
            return code;
        }

    }

    /**
     * Serialize CSV to {@link EnumMap}
     */
    @Test
    public void toEnumMapTest() throws IOException {
        String input = "x,y,Temp.,ND1,ND2\n12,3,way too hot,f,8\n12,3,way too hot,f,8\n12,3,way too hot,f,8";

        ObjectMapper mapper = new CsvMapper().enable(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE);
        CsvSchema schema = CsvSchema.emptySchema().withHeader();
        MapType javaType = mapper.getTypeFactory().constructMapType(EnumMap.class, HeaderField.class, String.class);

        MappingIterator<EnumMap<HeaderField, String>> it = mapper
                .readerFor(javaType)
                .with(schema)
                .readValues(input);

        while (it.hasNext()) {
            Map<HeaderField, String> row = it.nextValue();
            String xVal = row.get(HeaderField.X);
            String yVal = row.get(HeaderField.Y);
            String temperature = row.get(HeaderField.TEMPERATURE);
            // do something with the values
            assertEquals("12", xVal);
            assertEquals("3", yVal);
            assertEquals("way too hot", temperature);
        }
    }
```

**Comment by matthias-mueller** [comment]
May I ask for the reason why `ObjectMapper` - instead of generating null/default keys - cannot skip or discard values with missing keys entirely? Is it intended by design or an unavoidable consequence of Jackson's internal workings?

**Comment by cowtowncoder** [comment]
@matthias-mueller Yes, unfortunately the design is such that there typically is no option for individual (de)serializers (key or value) to "refuse" to read or write something they are expected to -- it is up to parent (de)serializer to handle skipping.
So there is no mechanism to ignore something like "let's just ignore this key/value".

That means that skipping, if any, needs to be handled at `Map`/`EnumMap` level.

**Comment by matthias-mueller** [comment]
> That means that skipping, if any, needs to be handled at Map/EnumMap level.

If I understand this statement correctly, a facade implementation in front of EnumMap could implement that kind of skipping/filtering logic - especially in conjunction with `DeserilizationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL`. - So lets assume for the moment that all unknown keys have been transformed to NULL values and the final task is to sort them out when putting new entries into the target maps.

I see two deserialization methods in `EnumMapDeserializer`:

```java
public T deserialize(JsonParser p, DeserializationContext ctxt);

public T deserialize(JsonParser p, DeserializationContext ctxt, T intoValue);
```

Since the first method is in full control of the returned object, it might have a chance to see additional Deserialization Features (let's call them `DeserilizationFeature.SKIP_NULL_KEYS`) and should be able to employ a proxy/facade in front of `java.util.EnumMap` which filters all NULL keys before they hit the proxied `EnumMap`. When deserialization is finished, it could return the proxied `java.util.EnumMap`, so the caller never sees the facade.

The second method is a bit different since the `EnumMap` target was already created externally. The approach from above would still work if deserialization created an intermediate (proxied) `EnumMap`, perform the above steps, and in a final step transfer all deserialized entries via `putAll()` to the target map. - While the Object creation overhead should be negligible, I am not so sure about the performance penalties of that additional `putAll()` operation.

(And of course I am completely unaware of the broader implications of the suggested `DeserilizationFeature.SKIP_NULL_KEYS` in Jackson)

**Comment by cowtowncoder** [comment]
Perhaps? I am not quite sure I follow the benefits of proxying here, over actually implementing the logic in `EnumMapDeserializer`.

But as to more general `DeseriliazationFeature.SKIP_NULL_KEYS`, that would be doable and perhaps something worth adding, given that a few other `Map` types (specifically, Guava's Maps and I think maybe even `ConcurrentHashMap`?) fail if `null` key was to be used.
And it'd be acceptable addition to `DeserializationFeature` since it is not "too targeted" setting (I do have plans to actually add other targeted features: see hypothetical JSTEP-7 on https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP).

**Comment by matthias-mueller** [comment]
Since `null` keys are an odd choice for any `Map` key and usually cause trouble for consumers (https://stackoverflow.com/a/45210670) it might be a good choice to have a `DeserilizationFeature.SKIP_NULL_KEYS` switch for all MapDeserializers.

However, what I am really looking for is a clean way to tell the ObjectMapper to skip missing keys - which seems impossible at the moment. There is an existing workaround for `(Linked)HashMap` with the option `DeserilizationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL`. A similar workaround for `EnumMap` would require an additional switch to silently drop illegal keys - hence the proposal.
While I write this down, both workarounds seem a bit hacky since you have just pointed out that NULL keys do have a meaning in Jackson.

A better flag would be `DeserilizationFeature.FAIL_ON_UNKNOWN_KEYS = true|false` or `DeserilizationFeature.SKIP_UNKNOWN_KEYS = true|false` which is more in line with the already existing `@JsonIgnoreProperties(ignoreUnknown = true|false)`.

I think that `@JsonIgnoreProperties` (or `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES`) would be sufficient to express the desired behaviour for missing keys since `Map` keys are in fact property names. - One could argue that ignoring these flags/annotations in `Map` deserialization is unexpected behaviour.

(And yes, I agree that facades are not the ideal option to filter keys before they hit the actual map - please treat them as an illustration).

**Comment by cowtowncoder** [comment]
At this point, this issue would properly belong in `jackson-databind`. Could you file it there? I think `SKIP_UNKNOWN_MAP_KEYS` would make sense (it is slightly redundant as only `Map`s have keys, but it seems reasonable to me wrt existing feature naming).
