### ISSUE TITLE
Default YAML mapper quotes "y" as a key

### ISSUE THREAD

**Issue by tcrespog** [FasterXML/jackson-dataformats-text#278]
Hi, after upgrading from the `2.11.4` version of the library to the `2.12.x` line I've noticed that a default YAML mapper...
```java
ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
```
...is quoting the `y` character when found as a key, whereas other single character keys (or longer string keys for that matter) are not being quoted. For example, the code...
```java
ObjectMapper defaultMapper = new ObjectMapper(new YAMLFactory());

Map<String, Integer> map = new HashMap<>();
map.put("x", 1);
map.put("y", 2);
map.put("z", 3);
defaultMapper.writeValueAsString(map);
```
...generates the YAML...
```yml
---
x: 1
"y": 2
z: 3
```
...whereas using `2.11.4` it generates:
```yml
---
x: 1
y: 2
z: 3
```

What is the reason behind such new behavior? Thanks.

(I've uploaded a sample repo (https://github.com/tcrespog/jackson-yml-test) with a simple test that reproduces the aforementioned behavior)

**Comment by tcrespog** [comment]
I think I've found the rationale behind this behavior in these links:
- https://github.com/FasterXML/jackson-dataformats-text/blob/2.12/yaml/src/main/java/com/fasterxml/jackson/dataformat/yaml/util/StringQuotingChecker.java#L26
- https://github.com/FasterXML/jackson-dataformats-text/pull/225
- https://github.com/FasterXML/jackson-dataformats-text/issues/226
- https://yaml.org/type/bool.html

I'm closing the issue then. Sorry for the noise and thanks all the same.

**Comment by cowtowncoder** [comment]
No problem -- yes, it is a  YAML oddity needed to avoid accidental coercion. Glad you found out the answer!
