### ISSUE TITLE
Parsing of YAML content fails if value starts with special characters "+-" or "~"

### ISSUE THREAD

**Issue by mrbenjoi** [FasterXML/jackson-dataformats-text#281]
I might have found a bug, that I'd like to report.

**Problem:**
The following YAML-content cannot be parsed with Jackson.

```yaml
template:
    amplitude: 5
    noise: +-0.01  
```

This fails with this exception:

```
com.fasterxml.jackson.databind.JsonMappingException: empty String (through reference chain: ... ->my.package.Template["noise"])
```

If I prepend a "0" before "+-", it works flawlessly:

```yaml
template:
    amplitude: 5
    noise: 0+-0.01
```
The same problem occurs, when I use `noise: ~0.01`. The same exception is thrown on this and can be avoided by prepending a "0" before the curly "~".

**Background info:**
My class `Template` contains a property `noise` of type `FlexValue`. I made a custom `JsonDeserializer` that is responsible to parse the values for properties of this type. The notation allows somewhat fancy expressions, hence the name `FlexValue` for the type. The value in this example, "+-0.01", is a valid input for the deserializer, so is "~0.01".  **However, it seems like the deserializer isn't even called. The exception seems to be thrown before that.**

**Expected behavior:**
As far as I know, the literals "+-" and "~" are not special sequences in YAML, which might have explained the described behavior (although I might be wrong about that premise, of course). My expectation therefore is that these values should be parsed as strings and made available to custom deserializers as such, since they both don't represent valid numerical values.

I use Jackson in Kotlin with Gradle. My Jackson dependencies are as follows:
```
    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.4")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.4")
```

**Comment by mrbenjoi** [comment]
I wasn't able to add Labels for some reason. I suggest yaml and bug if they are available.

**Comment by cowtowncoder** [comment]
@mrbenjoi could you include bit of code that reads YAML value; and if target is a POJO, definition of that POJO class?

**Comment by mrbenjoi** [comment]
@cowtowncoder Thanks for reaching out. While trying to create a failing example I found the reason of the problem, which had nothing to do with Jackson. Sorry for the noise.

**Comment by cowtowncoder** [comment]
@mrbenjoi Ok. Was about to get back to this issue and ask for details; there is some auto-detection for `~` (as it's `null` value). But glad you figured out the root cause.
