### ISSUE TITLE
rework sonatype publishing (github action)

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-dataformats-text#284]
* https://github.com/FasterXML/jackson-dataformats-text/blob/2.13/.github/workflows/main.yml will need to be reworked for non-snapshot builds - it looks the job will try to publish unsigned jars when a commit is done to a branch and the version number is not a snapshot version but sonatype only allows snapshot jars not to be signed
* it would be better to sign all jars that are published to sonatype anyway
* https://github.com/olafurpg/sbt-ci-release has a good description of how to create a GPG key and add the secrets to github

**Comment by cowtowncoder** [comment]
Yes, CI should never try to publish non-snapshot versions: releases are handled outside of CI as things are.
I am not sure how to do that however. GPG signing would be nice too, but I do not want release versions to be accidentally pushed by CI so that needs to be solved first.

**Comment by pjfanning** [comment]
@cowtowncoder this is completely untested but changing main.yml to something like this might work

```
      run: |
        export POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) \
        if [[ $POM_VERSION == *"-SNAPSHOT"* ]]; then ./mvnw -V -B -ff -DskipTests -ntp source:jar deploy; fi
```

I think `run: |` allows you to have multi-line run commands - I think you need `\` at end of each line (https://stackoverflow.com/questions/59954185/github-action-split-long-command-into-multiple-lines)

I tried to squash the condition onto one line and I'm not sure the syntax is fully correct but it seems to work on my Macbook.

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson-dataformats-text/blob/2.14/.github/workflows/main.yml looks like it restricts publishing to just snapshot versions

**Comment by cowtowncoder** [comment]
@pjfanning Yes. I forgot we had an actual ticket here, thanks!
