### ISSUE TITLE
Caching conflict when creating CSV schemas with different views for the same POJO

### ISSUE THREAD

**Issue by mrpiggi** [FasterXML/jackson-dataformats-text#288]
#195 added csv schema creation with views. Using the same CsvMapper with the same POJO for different views leads to unexpected results as the used view is not considered when a schema is loaded from cache as it was registered for the pojoType. Obviously, the used view should be part of the key for the cache maps `_untypedSchemas` and `_typedSchemas`.

https://github.com/FasterXML/jackson-dataformats-text/blob/1202fec8d6243da77435fc723162d738acb1c8ad/csv/src/main/java/com/fasterxml/jackson/dataformat/csv/CsvMapper.java#L425-L433

Edit: A workaround is quite simple. In order to clear the cache, just use `csvmapper.copy().schemaForWithView(...)` instead of `csvmapper.schemaForWithView(...)`.

**Comment by cowtowncoder** [comment]
Oh. Yes indeed... Gnarly one, this.

**Comment by mrpiggi** [comment]
In my eyes, caching only when `view==null` would be a sufficient fix for `2.13`

**Comment by cowtowncoder** [comment]
Fixed for upcoming 2.13.1 by simply skipping caching if view enabled. May be improved in future if someone has an itch; just need to change key for cache.

**Comment by mrpiggi** [comment]
What would be suitable to create a corresponding key from `JavaType pojoType` and `Class<?> view` for `LRUMap`? Is there already a generic tuple or something similar to the existing `TypedKey` integrated in `jackson-core` or `jackson-databind` that could be used for this purpose or would a new class (`ViewKey`?) be necessary?

**Comment by cowtowncoder** [comment]
I can't think of a type and since we cannot add 3rd party `Pair` or `Tuple`, would need a simple key class like `ViewKey`.
@mrpiggi if you have time and interest I'd be happy to help merge this to 2.14.

`jackson-databind` probably has some similar class already fwtw, for (de)serializer caching. Not with exact types but similar.

**Comment by mrpiggi** [comment]
Sure, I can try to find some time. Should I create a PR based on `2.13` or `2.14`? Are there any contribution guide lines?

**Comment by cowtowncoder** [comment]
2.14: keeping caching simple for 2.13 patch just in case. 

There isn't a lot about contributing, just this:

https://github.com/FasterXML/jackson/blob/master/CONTRIBUTING.md
