### ISSUE TITLE
Jackson adding "---" in front of parsed yaml.

### ISSUE THREAD

**Issue by Trqhxrd** [FasterXML/jackson-dataformats-text#289]
Hey guys.

I want to use jackson but everytime I parse an object, the returned string starts with "---". I can remove the three dashes but it would be much more convenient, if there was an option in the ´YamlFactoryBuilder´. If there is, please tell me.

Thank you for your help!
- Trqhxrd

**Comment by cowtowncoder** [comment]
Ok, I think what you mean is about writing/generation of YAML and not parsing (parsing is reading YAML into Java), and you would like the `---` YAML document prefix not to be written?
This can be done by disabling `YAMLGenerator.Feature.WRITE_DOC_START_MARKER` (enabled by default).

Depending on code you use, you can either disable it on `YAMLFactory`:

```
YAMLFactory f = YAMLFactory.builder()
   .disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)
   .build();
```

or with databinding, use `ObjectWriter` to configure

```
YAMLMapper mapper = new YAMLMapper();
String yaml = mapper.writer().without(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)
    .writeValueAsString(value);
```

**Comment by Trqhxrd** [comment]
Thank you
