### ISSUE TITLE
FileInpuStream created but not closed if an error occur.

### ISSUE THREAD

**Issue by willome** [FasterXML/jackson-dataformats-text#29]
- Jackson-dataformat-csv version 2.8.8

When using `csvMapper.readValues(file)`, a new `FileinputStream` is created, but if an error occur during the parsing, this inputStream is never closed.

**Comment by cowtowncoder** [comment]
There is nothing specific in csv module here, so I assume this would be general problem.

Looks like `readValue()` variants should handle closing, but the `readValues(...)` is more complicated thing, returning `MappingIterator`. Challenge here is that there are many more code paths to keep track of, and it is not possible to use auto-closing (given that individual reads are not to close the parser).

So... could you please re-file at `databind`, for the general case, referring this issue?

**Comment by willome** [comment]
Opened on databind : https://github.com/FasterXML/jackson-databind/issues/1743
