### ISSUE TITLE
Keep data type when convert Properties to JsonNode

### ISSUE THREAD

**Issue by MinhTranQuang258** [FasterXML/jackson-dataformats-text#290]
Currently, I'm having trouble converting `Properties `to `JsonNode`. The converted value of `JsonNode `doesn't keep the original data type but always returns String type 

For example:

**Properties:**
  `metaData.output.enabled=true`  _// _true is boolean__

**JsonNode:**
```
{
  "metaData": {
      "output": {
         "enabled": "true"
      }
   }
}
```

Is there any way to fix them?

**Comment by yawkat** [comment]
Properties don't have data types other than `String`. From [the javadoc](https://docs.oracle.com/javase/9/docs/api/java/util/Properties.html):

> Each key and its corresponding value in the property list is a string. 

Values like `true` aren't boolean, they're still just strings. The application has to handle any transformation to another data type.

If you use a statically typed bean structure, e.g. a `class Output { public boolean enabled; }` and deserialize to that, jackson will parse the boolean value like you want.

**Comment by MinhTranQuang258** [comment]
Thanks for your respond. But I also see the `JavaPropsMapper` has a function: 

`readMapAs(Map<String, String> map, Class<T> valueType)`

Why is the first parameter is `Map<String, String> map` instead of `Map<String, Object> map`?

In my case, if the first parameter is `Map<String, Object> map` then I can use this function like below:

```
    public static void main(String[] args) throws IOException {
        
        final Map<String, Object> map = new HashMap<>();
        map.put("metaData.output.enabled", true);   // true is boolean
        
        final JavaPropsMapper mapper = JavaPropsMapper.builder().build();
        
        final JsonNode node = mapper.readMapAs(map, JsonNode.class);
    }
```

Expect result:

```
{
  "metaData": {
      "output": {
         "enabled": true // true is boolean
      }
   }
}
```
I know that the application may have to do some deserialization to convert the String to Boolean, but I think the library should support this feature, right?

**Comment by MinhTranQuang258** [comment]
I mean `JavaPropsMapper` will probably support a function like this:

`readMapAs(Map<String, Object> map, Class<T> valueType)`

And expect the Json to keep the original data type

**Comment by cowtowncoder** [comment]
@MinhTranQuang258 I think @yawkat is correct wrt incoming data. I know JDK `Properties` has historical oddity that non-String values are allowed, but Jackson does not support that.

But aside from that, at this point I'd need to see piece of code (like unit test) to show what you consider to be the problem: textual descriptions can be helpful but often omit something necessary. So code is better at pinpointing the exact issue.

**Comment by cowtowncoder** [comment]
Exact problem not clear, closing. May be re-opened/re-filed with explanation.

**Comment by samir-lab** [comment]
您好，邮件已收到，会尽快给您回复。
