### ISSUE TITLE
Column order is incorrect and nondeterministic when writing to CSV with capital letters

### ISSUE THREAD

**Issue by JacobGH111** [FasterXML/jackson-dataformats-text#295]
When serializing to a CSV the column order output is incorrect but **only when one or more attributes has a capital letter**. The output order is also **nondeterministic**. Two back-to-back runs with the exact same values can produce different output orders.

Code to reproduce bug (Kotlin):
```
package com.draper.surveillance.common

import com.fasterxml.jackson.annotation.JsonPropertyOrder
import com.fasterxml.jackson.databind.MapperFeature
import com.fasterxml.jackson.databind.ObjectWriter
import com.fasterxml.jackson.dataformat.csv.CsvMapper
import java.io.File


class MyClass(
   val zProp1: Int,
   val Prop2: Int,
   val Prop3: Int)

val csvMapper = CsvMapper().apply {
   disable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY)
}
val bootstrapSchema = csvMapper.schemaFor(MyClass::class.java)
   .withUseHeader(true)
val writer: ObjectWriter = csvMapper
   .writerFor(MyClass::class.java)
   .with(bootstrapSchema)

val sequenceWriter = writer.writeValues(File("test.csv"))
object Test {
   val l = listOf(
      MyClass(1,2,3),
      MyClass(4,5,6)
   )

   @JvmStatic
   fun main(args: Array<String>) {
      sequenceWriter.writeAll(l)
   }

}
```

Running the `main` method multiple times will result outputs with different orders.  If the property names in `MyClass` are changed to all lowercase then the issue disappears.
This issue has been confirmed to happen in Java as well, version `2.13.0`.  See [this](https://stackoverflow.com/questions/70037422/kotlin-jackson-serilization-wrong-column-order-and-nondeterministic?noredirect=1#comment123816936_70037422).

**Comment by cowtowncoder** [comment]
Your bug is here:

```
disable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY)
```

Do NOT disable this. It is not meant to be disabled, ever, at all, for CSV. There is the specific reason for keeping it enabled.

**Comment by cowtowncoder** [comment]
Put another way: your settings override causes the ordering instability since JDK accessors for fields, methods do not provide stable ordering.

Will close unless there is an actual issue.

**Comment by JacobGH111** [comment]
So is there no way to specify the column output order when writing a CSV?

**Comment by JacobGH111** [comment]
So is there no way to specify the column output order when writing to CSV?  Specifically is there any way to do it without hard-coded strings that must be kept in sync manually with the names of the properties?

**Comment by cowtowncoder** [comment]
There are certainly are ways to define ordering of fields.

Most commonly you:

1. Use annotations (`@JsonPropertyOrder` -- never mind "Json" there that's legacy -- on POJOs)
2. Build `CsvSchema` manually adding column definitions in order
3. Use the first line of CSV file, so-called "header", to define order.
4. Use `@JsonProperty(index = X)` to define order based on `index` of individual properties
5. If anything else fails you can implement `AnnotationIntrospector` that determines different ordering based on whatever logic you want

I don't know if you have seen this but it might help wrt usage:

https://cowtowncoder.medium.com/reading-csv-with-jackson-c4e74a15ddc1

I hope this helps.

**Comment by JacobGH111** [comment]
Thank you, this is tremendously helpful and now I understand why this is not a bug but just a limitation of the JVM.

**Comment by cowtowncoder** [comment]
Right: earlier JDKs tended to return Fields and Methods in order but even that is not guaranteed and apparently has lately been changing. In addition, combination ordering across Fields/Methods is not defined and use of inheritance can basically make it impossible to find out full declaration order anyway.
In hindsight it would probably have made for Jackson to default to alphabetic ordering from version 1.0. But at the time it was not as obvious as later on; and wasn't as much an issue with JSON anyway as ordering should not have semantic meaning. This is definitely different with positional formats like CSV.

**Comment by seanf** [comment]
A fix for https://github.com/FasterXML/jackson-dataformats-text/issues/264 would allow Java records as another solution for the ordering problem, since record components do have a defined order.
