### ISSUE TITLE
(yaml) Does not handle octal or hexadecimal representations of integers

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#3]
(from: https://github.com/FasterXML/jackson-dataformat-yaml/issues/37 by @jvantuyl)

The use of BigInteger for really big integers introduces an interesting behavior.  For a very large zero-prefixed number, it won't see a leading zero as indicating octal (because BigInteger's constructor doesn't mirror Integer.parseInt or Long.parseLong).

In the long run, also doesn't support the 0o644 notation from YAML 1.2, which I'm starting to see floating about.

**Comment by jcalcote** [comment]
Just a comment on how important this item is - when you're serializing configuration data from pojos and you have fields that represent large sizes - e.g., memory, file sizes, etc. - hex numbers look a lot cleaner and mean more to the reader than decimal values. I wrote customer serializers and deserializers for long and int so I could output such fields in hex and read in whatever, but it would be nice if Jackson both supported all yaml scalar formats AND provided field annotations that allowed the developer to specify the radix for serialized values. Thanks for the great project, btw.

**Comment by cowtowncoder** [comment]
@jcalcote If you had interest in helping here it would be great to know why SnakeYAML does not support such values at this point; and if there was a way to configure it to do that. Challenge is that since `jackson-databind` at higher level is format agnostic it is not easy to apply coercions from hex-strings since those would typically be unexpected with other formats. So ideally it'd be low-level parser (provided by SnakeYAML) that would do coercion; we could also further have `YAMLParser.Feature`s to enable/disable such behavior if necessary.

**Comment by cowtowncoder** [comment]
Update: SnakeYAML DOES support these, as expected. Problem is more similar to #65 and code needs to be improved to handle binary/octal/hex/60-base variants, as per:

http://yaml.org/type/int.html

**Comment by Vlatombe** [comment]
This does seem to be a problem with SnakeYAML. AFAICS, the only coercion to int it does is in base 10 (https://bitbucket.org/asomov/snakeyaml-engine/src/e2a56f68077bedb66f0bab18e46f9a6996cb5bbd/src/main/java/org/snakeyaml/engine/v2/resolver/JsonScalarResolver.java#lines-36). As noted in its [documentation](https://bitbucket.org/asomov/snakeyaml-engine/wiki/Documentation#markdown-header-implicit-types), it only supports JSON schema to do coercion and not Core schema which would be required to support other int formats.

**Comment by cowtowncoder** [comment]
@Vlatombe ah. Based on other notes (including ones for #65) that does sound plausible. Not sure if I should close this issue.
There is also the thing about Jackson 3.0 using snakeyaml-engine, which I suspect also takes more restrictive view of allowed conversions, and probably won't support octal numbers either.

**Comment by cowtowncoder** [comment]
There is issue #71 for hexadecimal case, at least; closing this one.
