### ISSUE TITLE
The master branche does not compile

### ISSUE THREAD

**Issue by asomov** [FasterXML/jackson-dataformats-text#300]
@cowtowncoder I wanted to contribute but unfortunately (because of the merge from 2.* ???) the master branch does not compile. 
There are many compilations errors. I did not quite catch how I can resolve it myself (the change is too big)

**Comment by asomov** [comment]
By the way - which Java version is 3.0 going to support ? 8 or 11 ?

**Comment by cowtowncoder** [comment]
Ok I'll look at the issue, thank you for pointing it out.

As to 3.0, not decided, originally thougth Java 8 but given how much time has passed, very likely something later.

But I myself am bound to Java 8 at work so before jumping to Java 11 (or 14, one of LTS) I want to make sure my tooling works. And then handling module-info should become much easier.

For immediate future it is still Java 8, for practical purposes: but not intended to remain so. Does this make sense?

**Comment by cowtowncoder** [comment]
@asomov Build works on my system so I think I'd need some more information; bit of stack trace or something?
Specifical `mvn clean install` passes for me with JDK 8 and 11.

**Comment by asomov** [comment]
@cowtowncoder the choice of Java 8 has perfect sense for me. I am myself a library maintainer and I could not find any real reason to switch to Java 11
For compilation problem. The project has a parent, I pulled the latest changes (the master branch everywhere !) from the parent and rebuild all. I will do it again, may be I missed something.

**Comment by asomov** [comment]
@cowtowncoder I am terribly sorry. It was apparently my mistake. 
I did not want to get dependencies and built all the projects from source myself (including all the parent POMs)
Now it is all Ok. I think I made a mistake choosing a branch somewhere.

**Comment by cowtowncoder** [comment]
@asomov Ah. Not a problem at all -- sometimes there are issues so I'd rather have occasional false alarm. 

And as to Java 8, yes, I agree. For libraries like ones we maintain there is much more value in trying to use minimal/conservative choice for what we require.
