### ISSUE TITLE
YAML "LITERAL_BLOCK" will be quoted if there are trailing spaces in the content

### ISSUE THREAD

**Issue by carolkao** [FasterXML/jackson-dataformats-text#301]
Hi, I encountered a problem when using YAMLMapper with version 2.11.0.

When I try to deserialize the yaml content into an object and then convert it back to string, I found the literal block with 'trailing spaces' will be quoted. Like the following examples:

Input YAML content: (there are several spaces after 'multiline'.  "test for multiline   ")
```
name: "test"
description: |
  test for multiline   
  with trailing spaces
```

And the output will become:
```
name: "test"
description: "test for multiline   \nwith trailing spaces"
```

Currently, I can use IDE to help and remove all trailing spaces when saving the input file. But I'm still wondering if there is any workaround or some specific feature to retain the original format with trailing spaces? 

P.S I've tried to use version 2.13.0 but there is no luck, the issue still there.

Thanks,
Carol

**Comment by yawkat** [comment]
There is no way to keep the formatting the same as the input file. That data is simply not present in the object model after deserialization. Comments are also lost for example.

For your specific case, it seems like this is a snakeyaml thing. They don't allow spaces before breaks to occur in unquoted strings: https://github.com/spariev/snakeyaml/blob/master/src/main/java/org/yaml/snakeyaml/emitter/Emitter.java#L1047-L1051

I'm not familiar enough with yaml to say whether this is correct, [the spec](https://yaml.org/spec/1.1/#id907281) on this is a bit confusing. It kind of sounds like the spaces should be collapsed during parsing, but I'm not sure. Either way if this is a bug, it's on snakeyamls side.

**Comment by carolkao** [comment]
Hi @yawkat,

Thanks for your quick response. I got it.
I'll close this case since it's not the issue belong to jackson-dataformats-text. 

Appreciate your help :)
