### ISSUE TITLE
Update jackson-databind to version 2.13.2.1 

### ISSUE THREAD

**Issue by mr-zepol** [FasterXML/jackson-dataformats-text#310]
Is there any plans to update this version [jackson-databind-2.13.2.1](https://github.com/FasterXML/jackson-databind/releases/tag/jackson-databind-2.13.2.1), this includes the fix for  https://github.com/FasterXML/jackson-databind/issues/2816

**Comment by mgadek007** [comment]
And any plans to upgrade [jackson-databind - 2.13.2.2](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.13.2.2)?

**Comment by cowtowncoder** [comment]
No, this is not how micro-patches work. Intra-project dependencies are always across minor versions; micro-patches (with "extra" digit) are special cases and must either be explicitly indicated, or -- much better option -- included using appropriate date-stamp-versions `jackson-bom` version.

So basically once `2.13.3` is released, we'll get in-sync simple set, but until then, jackson-databind is a special case.

**Comment by pjfanning** [comment]
Can we close this now that 2.13.3 is released?
