### ISSUE TITLE
What is the correct way to escape the QuoteChar?

### ISSUE THREAD

**Issue by cgendreau** [FasterXML/jackson-dataformats-text#33]
I would like to escape the QuoteChar when it is doubled.

`1, " the next word is ""quoted"""`

The following snippet seems to give the expected result:
```
CsvSchema schema = CsvSchema.emptySchema()
.withQuoteChar('"')
//if we have a quote char, allow to escape it (see rfc4180)
.withEscapeChar('"')
...
```

But, the [csv-compatibility](
https://github.com/FasterXML/jackson-dataformats-text/tree/master/csv#csv-compatibility) section states : 

> If enabled, character immediately followed will be used as-is, except for a small set of "well-known" escapes (\n, \r, \t, \0)

**Comment by cowtowncoder** [comment]
I am not sure I follow the question: quote char is by default escaped by doubling it up.
So shouldn't it work the way you want already?

**Comment by cgendreau** [comment]
Indeed, it works already.

I started from `.withEscapeChar('\')` to handle things like `"1","{\"key\":\"value\"}"` where the json escape char was included in the csv. I was confused about what to use in `withEscapeChar` after the file was fixed to have `"1","{""key"":""value""}"`.

My bad

**Comment by cowtowncoder** [comment]
Ok. Just glad it works for you!
