### ISSUE TITLE
Problem with `YAMLGenerator.Feature.INDENT_ARRAYS`, nested Objects

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#34]
(see https://github.com/FasterXML/jackson-dataformat-yaml/issues/67 reported by @ondrej-kvasnovsky for discussion)

Looks like SnakeYAML (1.18 and below) have an issue with indentation, causing generation of invalid YAML in cases where array values are not scalars.

**Comment by cowtowncoder** [comment]
Ok, I fixed at least this specific problem. I have a nagging feeling this will not be full fix as it appears to rely on relationship between settings (in some way), and that perhaps some other nesting combinations might not work.
I chose values 1 and 2, although others would also work, but hard to guess which settings would be best. Also would be nice to allow more customization (maybe for jackson 3.0).

It does also slightly change indentation amounts, although since feature was only added in 2.9.0 may not matter a lot.

**Comment by arperalta3** [comment]
With the values 1 and 2, I have weird outputs like: 
```
tags:
 -
  name: test
  description: Testing.
```

But with 4 and 2 that is gone:
```
tags:
  - name: test
    description: Testing.
```

**Comment by cowtowncoder** [comment]
@arperalta3 Does it affect correctness, or just visual aspects?

**Comment by arperalta3** [comment]
@cowtowncoder Yes it does affect correctness, but I only can talk about swagger.

**Comment by cowtowncoder** [comment]
Ok, in that case another issue, unit test is needed. I can change default settings but regression test(s) are important esp. so for when there's new snakeyaml version to upgrade to.
