### ISSUE TITLE
Incorrect output buffer boundary check in `CsvEncoder`

### ISSUE THREAD

**Issue by k163377** [FasterXML/jackson-dataformats-text#343]
The following code is it.

https://github.com/FasterXML/jackson-dataformats-text/blob/9d8603ad475d1fe52d269ecf839064952594200d/csv/src/main/java/com/fasterxml/jackson/dataformat/csv/impl/CsvEncoder.java#L406-L410

I am not familiar with this code and could not investigate what specific defects it causes.

**Comment by cowtowncoder** [comment]
Interesting. Thanks, I'll check it out.

**Comment by cowtowncoder** [comment]
Yes, that should be:

```
if ((_outputTail + 12) > _outputEnd) {
```

and what would happen in the problem case is `ArrayIndexOutOfBoundsException` for some cases.
Not very commonly as this has not been reported but still.
Thanks!
