### ISSUE TITLE
Yaml: change of behavior with long String and minimize quotes (with version 2.11.0 and newer)

### ISSUE THREAD

**Issue by jmini** [FasterXML/jackson-dataformats-text#347]
With long `String` values with `YAMLGenerator.Feature.MINIMIZE_QUOTES` enabled, I have noticed the usage of quotes with some backslash `\` on new lines.

Example with `com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.10.5`:

```yaml
---
a: This is a test
b: |-
  Fooo
  Fizz
  Baarr
  Test
c: "43"
d: very long long long Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
  dignissim, velit in egestas consectetur, metus dui dignissim ipsum, et lacinia tellus
  purus vitae tortor. Vestibulum rhoncus ullamcorper eros, sit amet efficitur nulla
  hendrerit a. In posuere dignissim est at sollicitudin. Praesent suscipit placerat
  ligula, vitae pellentesque leo vestibulum eu. Aliquam in ante ac metus ultrices
  suscipit quis vitae erat. Maecenas feugiat sodales lectus quis elementum. Curabitur
  quis convallis mauris, eu vulputate nisi.
```

After the update `com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.11.0` (and newer):

```yaml
---
a: This is a test
b: |-
  Fooo
  Fizz
  Baarr
  Test
c: "43"
d: "very long long long Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec\
  \ dignissim, velit in egestas consectetur, metus dui dignissim ipsum, et lacinia\
  \ tellus purus vitae tortor. Vestibulum rhoncus ullamcorper eros, sit amet efficitur\
  \ nulla hendrerit a. In posuere dignissim est at sollicitudin. Praesent suscipit\
  \ placerat ligula, vitae pellentesque leo vestibulum eu. Aliquam in ante ac metus\
  \ ultrices suscipit quis vitae erat. Maecenas feugiat sodales lectus quis elementum.\
  \ Curabitur quis convallis mauris, eu vulputate nisi."
```

Is this expected?

----

Reproducer using [jbang](https://www.jbang.dev/):

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
	
//DEPS com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.11.0
//DEPS org.yaml:snakeyaml:1.33

import static java.lang.System.*;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

public class YamlExample {

    public static void main(String... args) throws Exception {
        YAMLFactory factory = YAMLFactory.builder()
            .enable(YAMLGenerator.Feature.MINIMIZE_QUOTES)
            .enable(YAMLGenerator.Feature.ALWAYS_QUOTE_NUMBERS_AS_STRINGS)
            .build();
        
        ObjectMapper mapper = new ObjectMapper(factory);

        ObjectNode tree = mapper.createObjectNode();
        tree.put("a", "This is a test");
        tree.put("b", "Fooo\nFizz\nBaarr\nTest");
        tree.put("c", "43");
        tree.put("d", "very long long long Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dignissim, velit in egestas consectetur, metus dui dignissim ipsum, et lacinia tellus purus vitae tortor. Vestibulum rhoncus ullamcorper eros, sit amet efficitur nulla hendrerit a. In posuere dignissim est at sollicitudin. Praesent suscipit placerat ligula, vitae pellentesque leo vestibulum eu. Aliquam in ante ac metus ultrices suscipit quis vitae erat. Maecenas feugiat sodales lectus quis elementum. Curabitur quis convallis mauris, eu vulputate nisi.");

        out.println("Test yaml document:");

        String value = mapper.writer()
            .writeValueAsString(tree);
        out.println(value);
    }
}
```

**Comment by cowtowncoder** [comment]
I do not recall any specific change that would cause this, but looking at 2.11.0 release notes perhaps fix for #180 changed handling? 
Alternatively it could be that SnakeYAML version used was changed and newer version changed encoding for some reason (Jackson delegates low level decoding and encoding to SnakeYAML).

Given that 2.11 was released a while ago, I think the new behavior will be considered the baseline by now, unless there is a specific issue (like logical content changed when writing, reading back).

**Comment by jmini** [comment]
Thank you for the very quick feedback.

I made all my tests with the latest SnakeYAML version `org.yaml:snakeyaml:1.33`… So the change is really on Jackson side.

---

For our use case (writing OpenAPI documention in YAML), the quote & backslashes are not user-friendly when the Yaml file is read directly by a human. We were happy with the `2.10.5` behavior even if according to the spec [1] linked in https://github.com/FasterXML/jackson-dataformats-text/pull/181 this was not correct.

[1] https://yaml.org/spec/1.2/spec.html#id2788859.

---

I think we will disable `SPLIT_LINES`. This way we will have the quotes (so that the produced YAML is valid, as forced by `2.11+`) and not have the backlashes (and a very long line… but a human reader can still use "Toogle Word Wrap" in his editor and computers don't care about long lines)

**Comment by cowtowncoder** [comment]
@jmini I hope disabling `SPLIT_LINES` works.

But beyond this I would definitely be open to something like:

1. Changing the detection logic for what requires quoting
2. Adding another `YAMLGenerator.Feature` to further control quoting aspects

or so. But for that to go in 2.14 (generally behavior changes need to go in minor releases) it'd need to be submitted soon.
I'd be happy to expedite PR, esp. for (2).

Of course this is fully optional if you feel like this; or anyone else with an itch.

Configuring output aspects is rather tricky with YAML it turns out...

**Comment by jmini** [comment]
This is the output with `SPLIT_LINES` disabled:

```yaml
---
a: This is a test
b: |-
  Fooo
  Fizz
  Baarr
  Test
c: "43"
d: "very long long long Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dignissim, velit in egestas consectetur, metus dui dignissim ipsum, et lacinia tellus purus vitae tortor. Vestibulum rhoncus ullamcorper eros, sit amet efficitur nulla hendrerit a. In posuere dignissim est at sollicitudin. Praesent suscipit placerat ligula, vitae pellentesque leo vestibulum eu. Aliquam in ante ac metus ultrices suscipit quis vitae erat. Maecenas feugiat sodales lectus quis elementum. Curabitur quis convallis mauris, eu vulputate nisi."
```

It works as expected… People reading the YAML directly will have a better experience than with the `\`. They will rely on their editor doing the work.

---

I understand that `MINIMIZE_QUOTES` no longer remove quotes for cases where they are mandatory (as defined in the Yaml spec).

And I am a little bit reluctant to add a feature that would say "don't use quotes to make the serialized document looks good for human reader, but not conform to the Yaml Spec" in Jackson… So I will not invest time on it.

So I will go with `SPLIT_LINES` disabled: https://github.com/OpenAPITools/empoa/issues/147

---

I think it is good to have this discussion somewhere in the project (the case is documented). If someone wants to reopen this issue and explore the possibilities you have described, this is possible.

Thank you for the very constructive feedback @cowtowncoder.
