### ISSUE TITLE
YAML: Subtype serialization doesn't write property specified by JsonTypeInfo

### ISSUE THREAD

**Issue by marinier** [FasterXML/jackson-dataformats-text#350]
Java 17
Jackson 2.13.4

If I specify to use a "type" property to distinguish subtypes, I am able to deserialize from YAML but serialization does not work.

Here's an example:

```java
import java.util.List;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;

public class Test {

    public static void main(String[] args) throws JsonMappingException, JsonProcessingException {
        ObjectMapper mapper = YAMLMapper.builder()
                .enable(SerializationFeature.INDENT_OUTPUT)
                .build();

        String yaml = """
                - type: Sub1
                - type: Sub2
                """;
        List<Base> knowledge = mapper.readerForListOf(Base.class).readValue(yaml);

        String result = mapper.writeValueAsString(knowledge);
        System.out.println(result);
    }

    @JsonTypeInfo(use = Id.NAME, include = As.PROPERTY, property = "type")
    @JsonSubTypes({
        @Type(value = Sub1.class, name = "Sub1"),
        @Type(value = Sub2.class, name = "Sub2")
    })
    static abstract class Base { }

    static class Sub1 extends Base { }

    static class Sub2 extends Base { }
}
```

This writes out:
```
---
- {}
- {}
```

Setting a breakpoint shows that the correct subtypes were deserialized, so that part is working.

**Comment by cowtowncoder** [comment]
I don't think this is YAML specific but rather you are hitting Java's Type Erasure issue if serializing root-level generic types (such as `List<T>`). You should be able to see the same problem with JSON.

The issue is that all Jackson sees is `List<?>` which is roughly same as `List<Object>` and so base type of `Object` is used -- it does not have `@JsonTypeInfo`.
Same problem does not affect deserialization since you explicitly specify full parametric type.

To avoid this issue there are 3 basic approaches:

1. Avoid generic types at root level: use a wrapper POJO with one property which can be generic. Something like `class ListWrapper { public List<Base> list; } }` etc
2. Use a non-generic sub-type to define List elements: `public class BaseList extends ArrayList<Base> { } -- if so, type will not be erased because it is specified by sub-classing
3. Construct writer with specific type: `objectMapper.writerFor(new TypeReference<List<Base>>() { });` and use that

Unfortunately due to Jackson's detection of base type for container types (`List`s, `Collection`s, `Map`s) there is no way to resolve this issue in a generic fashion.

**Comment by marinier** [comment]
Ok, sorry for my bad example. I was simplifying my real-world use case and I simplified too far. Here is an example that actually demonstrates the "issue", and it doesn't involve Lists at all.

```java
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;

public class Test {

    public static void main(String[] args) throws JsonMappingException, JsonProcessingException {
        ObjectMapper mapper = YAMLMapper.builder()
                //.enable(DeserializationFeature.UNWRAP_ROOT_VALUE)
                .enable(SerializationFeature.INDENT_OUTPUT)
                .build();

        String yaml = """
                    myBaseObj1: 
                        type: Sub1
                    myBaseObj2:
                        type: Sub2
                """;
        Wrapper wrapper = mapper.readValue(yaml, Wrapper.class);

        String result = mapper.writeValueAsString(wrapper);
        
        System.out.println("YAML output:");
        System.out.println();
        System.out.println(result);
        
        ObjectMapper jsonmapper = JsonMapper.builder()
                .enable(SerializationFeature.INDENT_OUTPUT)
                .build();
        result = jsonmapper.writeValueAsString(wrapper);
        
        System.out.println("JSON output:");
        System.out.println();
        System.out.println(result);
    }

    
    
    static class Wrapper {
        public Base myBaseObj1;
        public Base myBaseObj2;
    }
    
    @JsonTypeInfo(use = Id.NAME, include = As.PROPERTY, property = "type")
    @JsonSubTypes({
        @Type(value = Sub1.class, name = "Sub1"),
        @Type(value = Sub2.class, name = "Sub2")
    })
    static abstract class Base { }

    static class Sub1 extends Base { }

    static class Sub2 extends Base { }
}
```
The output is:
```
YAML output:

---
myBaseObj1: !<Sub1> {}
myBaseObj2: !<Sub2> {}

JSON output:

{
  "myBaseObj1" : {
    "type" : "Sub1"
  },
  "myBaseObj2" : {
    "type" : "Sub2"
  }
}
```

I put "issue" in quotes because I think I now understand what's happening. I was confused because I expected the YAML output to look like the input (namely, that it would have a `type` field in it), but instead it output `!<>` which was syntax I wasn't familiar with. I now see that this is a more YAML-ish way of specifying the type of an object, and in fact if I change the input to look like that, it works fine (e.g., the json output is the same).

**Comment by cowtowncoder** [comment]
Ah. Yes; there are 2 ways to deal with Type Ids in YAML module: "native" (which you see) and non-native (as property). It's controlled by:

* `YAMLGenerator.Feature.USE_NATIVE_TYPE_ID` (default: true)

and if you wanted the other style it can be disabled. But yes, this is more "YAML way".
