### ISSUE TITLE
Disabling `FAIL_ON_MISSING_HEADER_COLUMNS` has no effect

### ISSUE THREAD

**Issue by malteo** [FasterXML/jackson-dataformats-text#352]
Following a dependency upgrade to version `2.14.0` I get failing tests:

    Missing 1 header column: ["specs"]

I found https://github.com/FasterXML/jackson-dataformats-text/commit/88a278f03dea828d219215219bf27ad4c8e947d3 from the changelog, but toggling the feature doesn't disable the check (it's quite obvious from the code).

**Comment by cowtowncoder** [comment]
Too bad this was not caught during the lengthy Release Candidate period for 2.14.

Would it be possible to contribute a simple test to show the issue since we don't have one that works to catch this problem?

**Comment by malteo** [comment]
I opened a PR

**Comment by cowtowncoder** [comment]
Much appreciated! Added a note on CLA, looking forward to merging the fix!
