### ISSUE TITLE
Is there a way to disable some features from SnakeYaml

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#37]
(by @exbe https://github.com/FasterXML/jackson-dataformat-yaml/issues/85)

SnakeYaml converts some string values into Boolean while resolving input ([link](https://bitbucket.org/asomov/snakeyaml/src/04378d05777d21d114a9cdc24976ad49c8919222/src/main/java/org/yaml/snakeyaml/resolver/Resolver.java?at=default&fileviewer=file-view-default#Resolver.java-31:33))

```
 public static final Pattern BOOL = Pattern.compile("^(?:yes|Yes|YES|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF)$");
```
While it is useful feature, some yamls might be converted with wrong value. Think about country code "NO", which is Norway.

Is there a way to disable or have better control over this with YamlParser features?

PS
Workaround is simple, just surround value with quotes, e.g.
```
countries:
    - AU
    - "NO"
    - MOON
```

**Comment by cowtowncoder** [comment]
@exbe At this point no. Ideally SnakeYAML usage would be implementation detail (to allow use of alternate decoders in future, if anyone ever implements other as-fully-featured codecs :) ).
But at the same time, it would be good to expose meaningful variations.

So: I am open to improvement ideas. If one of existing JsonParser.Features worked, those could be used as API (and result in calling suitable setters). But I don't think there's anything that quite works.

**Comment by asomov** [comment]
You can configurre Resolver to ignore all boolean values except true and false

**Comment by cowtowncoder** [comment]
@asomov Thank you. It may need to be `YAMLParser.Feature` to work at low level; at databind level there is a setting for allowing scalar value coercion but that is bit too late (and/or does not know rules parser backend uses). Sounds like reasonable option, will need to see if this should go in 3.0 (ideally yes, since it'd be API addition; but ... that may be ways out).

**Comment by jeff-miller-cfa** [comment]
a workaround to this is to create a custom `Resolver` then override the `addImplicitResolver` method like below:

```
new Resolver() {
        @Override public void addImplicitResolver(Tag tag, Pattern regexp, String first) {
            if (tag.equals(Tag.BOOL)) {
                regexp = Pattern.compile("^(?:true|True|TRUE|false|False|FALSE)$");
                first = "tTfF";
            }
            super.addImplicitResolver(tag, regexp, first);
        }
    }
```

**Comment by asomov** [comment]
@jeff-miller-cfa I think it should be only true|false (this is also the default in snakeyaml-engine now)

**Comment by cowtowncoder** [comment]
This issue is bit too vague; for specific aspects to configure (or proposal for configuration system that does not tie module too tightly into underlying implementation), can file new issues.
