### ISSUE TITLE
Replace use of deprecated constructor of SnakeYAML `ParserImpl`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#370]

**Comment by pjfanning** [comment]
Does this relate to https://github.com/FasterXML/jackson-dataformats-text/commit/9f822fb3fb248784f72708c4a30a8bddf9a0dc16 ? -- fixed in v2.14.2

**Comment by cowtowncoder** [comment]
@pjfanning Correct, forgot to close, was included in release notes.
