### ISSUE TITLE
Should verify that escape character set if enabling `CsvGenerator.Feature.ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR`

### ISSUE THREAD

**Issue by SebastianSolidwork** [FasterXML/jackson-dataformats-text#374]
Version: 2.14.1

I have a line like this, having quote chars in the data, create by JacksonCSV:
"\\"The\\"";"123"

which throws this while reading it also with JacksonCSV:
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('T' (code 84)): Expected column separator character (';' (code 59)) or end-of-line
 at [Source: (StringReader); line: 2, column: 5] (through reference chain: java.util.ArrayList[0])
```
Code of the writer:
```
        CsvSchema schema = CsvSchema.emptySchema().withColumnSeparator(';' as char)
                .withNullValue('null')
        CsvMapper CSV_MAPPER = CsvMapper.builder()
                .enable(CsvGenerator.Feature.ALWAYS_QUOTE_STRINGS)
                .enable(CsvGenerator.Feature.ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR)
                .build()
        String csv = CSV_MAPPER.writer(schema).writeValueAsString(lines)
```
Code of the reader:
```
        CsvSchema schema = CsvSchema.emptySchema().withColumnSeparator(';' as char).withNullValue('null')
        CsvMapper mapper = CsvMapper.builder()
                .enable(CsvGenerator.Feature.ALWAYS_QUOTE_STRINGS)
                .enable(CsvGenerator.Feature.ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR)
                .enable(CsvParser.Feature.WRAP_AS_ARRAY)
                .build()

        MappingIterator<List<String>> it = mapper
                .readerForListOf(String.class)
                .with(schema)
                .readValues(file.text);
        List<List<Object>> headerAndRows = it.readAll();
```
I thought that ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR would do the trick and I do not get why. Could you help me here?

I have attached [stacktrace.txt](https://github.com/FasterXML/jackson-dataformats-text/files/10446362/stacktrace.txt)

**Comment by cowtowncoder** [comment]
Ok I'd like to help but what is still missing is either full code to reproduce the problem, or reader part with embedded input.
Stack trace won't be of much help without being able to replicate what is happening.

Would it be possible to add that information?

**Comment by SebastianSolidwork** [comment]
Thanks for your help!

This is my Groovy script file reduced to the necessary parts to reproduce the bug.
Place it in a file named differently e.g. BugRepo.groovy
```
import com.fasterxml.jackson.databind.MappingIterator
import com.fasterxml.jackson.dataformat.csv.CsvGenerator
import com.fasterxml.jackson.dataformat.csv.CsvMapper
import com.fasterxml.jackson.dataformat.csv.CsvParser
import com.fasterxml.jackson.dataformat.csv.CsvSchema

@Grab(group = 'com.fasterxml.jackson.dataformat', module = 'jackson-dataformat-csv', version = '2.14.1')
@GrabConfig(systemClassLoader = true)

class BugRepo {
    static ArrayList<String> content = [['col1', 'col2'], ['"The"', 'foo']];

    static void main(String[] arg) {
        System.println(reader(writer(content)));
    }

    static List<List<String>> reader(String csvString) {
        CsvSchema schema = CsvSchema.emptySchema().withColumnSeparator(';' as char).withNullValue('null');
        CsvMapper mapper = CsvMapper.builder()
                .enable(CsvGenerator.Feature.ALWAYS_QUOTE_STRINGS)
                .enable(CsvGenerator.Feature.ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR)
                .enable(CsvParser.Feature.WRAP_AS_ARRAY)
                .build();

        MappingIterator<List<String>> it = mapper
                .readerForListOf(String.class)
                .with(schema)
                .readValues(csvString);
        return it.readAll();
    }

    static String writer(ArrayList<String> content) {
        CsvSchema schema = CsvSchema.emptySchema().withColumnSeparator(';' as char)
                .withNullValue('null');
        CsvMapper CSV_MAPPER = CsvMapper.builder()
                .enable(CsvGenerator.Feature.ALWAYS_QUOTE_STRINGS)
                .enable(CsvGenerator.Feature.ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR)
                .build();
        return CSV_MAPPER.writer(schema).writeValueAsString(content);
    }
}
```
I also tried to convert that code to Java. I can not execute it, but my compiler did not complained.
```
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.MappingIterator;
import com.fasterxml.jackson.dataformat.csv.CsvGenerator;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvParser;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;

public class BugRepoJava {
    static List<String> header = Arrays.asList("col1", "col2");
    static List<String> row1 = Arrays.asList("\"The\"", "foo");
    static List<List<String>> content = Arrays.asList(header, row1);

    static void main(String[] arg) throws IOException {
        System.out.println(reader(writer(content)));
    }

    static List<List<String>> reader(String csvString) throws IOException {
        CsvSchema schema = CsvSchema.emptySchema().withColumnSeparator(';').withNullValue("null");
        CsvMapper mapper = CsvMapper.builder()
                .enable(CsvGenerator.Feature.ALWAYS_QUOTE_STRINGS)
                .enable(CsvGenerator.Feature.ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR)
                .enable(CsvParser.Feature.WRAP_AS_ARRAY)
                .build();

        MappingIterator<List<String>> it = mapper
                .readerForListOf(String.class)
                .with(schema)
                .readValues(csvString);
        return it.readAll();
    }

    static String writer(List<List<String>> content) throws JsonProcessingException {
        CsvSchema schema = CsvSchema.emptySchema().withColumnSeparator(';')
                .withNullValue("null");
        CsvMapper CSV_MAPPER = CsvMapper.builder()
                .enable(CsvGenerator.Feature.ALWAYS_QUOTE_STRINGS)
                .enable(CsvGenerator.Feature.ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR)
                .build();
        return CSV_MAPPER.writer(schema).writeValueAsString(content);
    }
}
```

**Comment by cowtowncoder** [comment]
Ok; definitely looks like a bug on decoder (reading side). Will try to figure it out.

**Comment by cowtowncoder** [comment]
@SebastianSolidwork Ah. So the problem is that by default on reader side no Escape character is defined. So what you need to use is:

```
        CsvSchema schema = CsvSchema.emptySchema().withColumnSeparator(';').withNullValue("null")
                .withEscapeChar('\\');
```

and that, I think, resolves your problem.

Without this what happens is that character `\` is simply seen to be included in quotes and returned as one value; and then following `T` is seen where a separator was expected.
Exception is not very descriptive, but not sure if it is possible to reliably detect such cases.

**Comment by SebastianSolidwork** [comment]
Thanks! It works with that.
I was not aware that for the reader ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR is not sufficient. Because the writer does the escaping without withEscapeChar().

Could it be that the writer has a default, but the reader not? At least by the results it looks like this.
While the [writing article](https://cowtowncoder.medium.com/writing-csv-with-jackson-204fdb3c9dac) says it has none: "Escape character, if any (default: none)"

**Comment by cowtowncoder** [comment]
@SebastianSolidwork that does seem a bit wonky indeed: for better or worse, reader- and writer-side configurations are separate -- except where configuration is part of `CsvSchema`.

I do think you are right wrt defaults; so enabling escaping implicitly uses/defines escape character.

I'd be open to document improvements (f.ex PR would be great!).

**Comment by SebastianSolidwork** [comment]
Do intend further changes for aligning the behavior?
Either giving the reader the same default configuration for a escape character. (I would prefer that)
Or removing the default from the writer.
Depending on that I would writer different things.

I do not know how to make a PR to your medium articles.

With the current state I would change the following:
"Escape character, if any (default: none) — change with schema.withEscapeChar()"
To:
"Escape character, if any (default for reader: none, default for writer: \) — change with schema.withEscapeChar()"

**Comment by cowtowncoder** [comment]
I didn't mean Medium article, although that is a fair point -- did I miss a setting there?

But as to settings: the problem is really that you enabled escaping on writer (and it then has a default); but you did not enable it on reader (which is done by specifying escape character).
The two are not linked so enabling escaping on writer cannot really affect reader behavior; there is no assumption (in Jackson general) that users always use both, or that settings are necessarily the same.

I understand this is inconvenient, and realistically I think escaping settings should probably only exist in `CsvSchema` -- and if so, that would be shared.
But I am just not sure how to improve current situation here.

**Comment by cowtowncoder** [comment]
`ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR` is writer-side-only feature: reader does not (and cannot) access it.
It is invisible, and there is connection between these sides.
But you do not need to set escape character separately: it is defined via `CsvSchema` which you can (and typically should) share between readers and writers.

But I think that perhaps `ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR` should NOT WORK AT ALL without escape character, there not being a default (as per documentation). That it happens to work without specifying escape character could be seen as a bug, I think.

Maybe I should add a setting to fail writes for this particular case.

**Comment by SebastianSolidwork** [comment]
> But I think that perhaps ESCAPE_QUOTE_CHAR_WITH_ESCAPE_CHAR should NOT WORK AT ALL without escape character, there not being a default (as per documentation). That it happens to work without specifying escape character could be seen as a bug, I think.

It think this would address the problem at the core.

**Comment by cowtowncoder** [comment]
Turns out that it is difficult to reliably verify configuration settings in 2.x, so added check in 3.0 for now (`master`) where generator instances are immutable.
