### ISSUE TITLE
Add feature flag to allow parsing "boolean" words as strings instead of booleans

### ISSUE THREAD

**Issue by axelniklasson** [FasterXML/jackson-dataformats-text#388]
Right now [YAMLParser._matchYAMLBoolean](https://github.com/FasterXML/jackson-dataformats-text/blob/2.15/yaml/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLParser.java#L637) provides no flexibility to avoid words that are considered booleans to be parsed as strings instead, which is actually sometimes the desired behaviour and a good candidate for a feature flag in my opinion. I therefore propose the following

- Introduce a new `YAMLParser.Feature` called `PARSE_TRUTHY_WORDS_AS_STRINGS` (open for suggestion on names)
- When enabling this flag, the following words (converted to lowercase) will be parsed as strings instead of booleans:
  - yes
  - no
  - on
  - off
  - y
  - n

Note that `false` and `true` will still be parsed as booleans.

Let me know what you think! I'll be happy to help out with a PR here.

Related issue: https://github.com/FasterXML/jackson-dataformats-text/issues/129

**Comment by cowtowncoder** [comment]
@axelniklasson Sounds reasonable, I would accept PR and help it get merged. Should go in 2.15 branch (new feature), could make it in 2.15.0 as we'll hope to start release-candidate phase soon.

**Comment by axelniklasson** [comment]
@cowtowncoder great, thanks for the quick response! I'll get started on the PR today.

**Comment by axelniklasson** [comment]
@cowtowncoder PR ready here https://github.com/FasterXML/jackson-dataformats-text/pull/389, let me know your thoughts!

**Comment by cowtowncoder** [comment]
Looks pretty good, will add notes over there. Thanks!
