### ISSUE TITLE
(yaml) YAML block/flow style output control

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#4]
(from https://github.com/FasterXML/jackson-dataformat-yaml/issues/52 by @cruisercoder)

Jackson provides some control over the generated YAML, such as MINIMIZE_QUOTES. It it would also be nice also have control over the block/flow style at any point during the generation. This can be implemented by controlling the value of the style boolean that is passed to the snakeyaml Emitter.emit call.

**Comment by voddan** [comment]
+1 for this feature. Something like `LITERAL_BLOCK_STYLE` switch, but for lists would be great

**Comment by cowtowncoder** [comment]
Also too vague: needs to be refiled with more details; and possible updated wrt latest version which do have new options.

**Comment by marceloverdijk** [comment]
I understand this issue was closed but maybe something has changed since then.

I have a yaml output that contains:

```
      rounds:
        - 2
        - 4
        - 5
        - 7
```

In most cases I prefer every item on a new line, but for only this specific field I would prefer `[2, 4, 5, 7]` instead.

Is it possible to specify the format per field? E.g. with the mentioned `@JsonFormat` annotation?

**Comment by cowtowncoder** [comment]
Unfortunately no; the way `@JsonFormat` is defined, there isn't anything immediately applicable.

This is an area that would be great to improve, somehow; new TOML backend could also benefit from ability to control some aspects of formatting / structuring.

One challenge is that there are something like 5 styles, I think, so adding simple on/off features (for example) probably won't work. But choices to use are quite backend-specific, making it difficult to create general-purpose mechanisms

**Comment by marceloverdijk** [comment]
Thx for update!
