### ISSUE TITLE
NoSuchMethodError createContentReference

### ISSUE THREAD

**Issue by SK-Yang** [FasterXML/jackson-dataformats-text#419]
Asked on [stackoverflow](https://stackoverflow.com/questions/76251440/jackson-dataformat-csv-nosuchmethoderror-createcontentreference) too.

I'm using jackson-dataformat-csv 2.15.0 with following code to export my data into an text file

            List<HashMap<String, String>> data = <list of data>;
            PrintWriter out = new PrintWriter(new File(FILE_PATH));
            CsvSchema schema = null;
            CsvSchema.Builder schemaBuilder = CsvSchema.builder();
            // output verify list record
            if (data != null && !data.isEmpty()) {
                schema = schemaBuilder.addColumn("ID").addColumn("Date").build()
                        .withLineSeparator("\r").withHeader();

                CsvMapper mapper = new CsvMapper();
                mapper.writer(schema).writeValues(out).writeAll(data);
            }
            out.close();

But it just pop up error

        2023-05-14 14:11:25,865 ERROR [stderr] (Thread-394) Exception in thread "Thread-394" java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.csv.CsvFactory._createContentReference(Ljava/lang/Object;)Lcom/fasterxml/jackson/core/io/ContentReference;
        
        2023-05-14 14:11:25,865 ERROR [stderr] (Thread-394)     at com.fasterxml.jackson.dataformat.csv.CsvFactory.createGenerator(CsvFactory.java:372)
        
        2023-05-14 14:11:25,865 ERROR [stderr] (Thread-394)     at com.fasterxml.jackson.dataformat.csv.CsvFactory.createGenerator(CsvFactory.java:16)
        
        2023-05-14 14:11:25,865 ERROR [stderr] (Thread-394)     at com.fasterxml.jackson.databind.ObjectWriter.createGenerator(ObjectWriter.java:703)
        
        2023-05-14 14:11:25,865 ERROR [stderr] (Thread-394)     at com.fasterxml.jackson.databind.ObjectWriter.writeValues(ObjectWriter.java:789)

Doesn't seem to be I have conflicts with old jackson libs that this CSV lib required. And when I open declaration of createGenerator(), my Eclipse would take me to JsonFactory class, not CsvFactory class. So I assume there is something mess up? I need help.

**Comment by cowtowncoder** [comment]
This suggests that you have an older version of `jackson-core` than 2.15. Method seems to have been added in 2.13, so perhaps it's very old. But in general exception like this is an indication of version mismatch between Jackson components: the recommendation is to always match minor version of all Jackson components.

But in case of CSV module which depends on `jackson-databind` and `jackson-core`: versions of things depended on must be at least same or higher than version of thing that depends on them. So if CSV module version 2.15 is used, core and databind should be 2.15 or higher (and 2.15 being the latest version, 2.15).

**Comment by SK-Yang** [comment]
> But in general exception like this is an indication of version mismatch between Jackson components: the recommendation is to always match minor version of all Jackson components.

huh? I have checked my WAR's WEB-INF/lib folder and there isn't any duplicated lib name `jackson-databind` and `jackson-core`. Unless... it is outside of my WAR

**Comment by cowtowncoder** [comment]
@SK-Yang Nonetheless somehow you have version incompatibility across Jackson components. There's not much we can do to help with that aside from pointing out the likely root cause.
