### ISSUE TITLE
How to combine props and json dataformat

### ISSUE THREAD

**Issue by anuragagarwal561994** [FasterXML/jackson-dataformats-text#424]
I have a use-case where my property files may contain json values, for example:

```
prop1.value={"a": "b"}
```

Can this be represented as:
```
class Obj {
    private Prop prop1;
   
    private static class Prop {
          private JsonObj value;
    } 

    private static class JsonObj {
          private String a;
    }
}
```

I might need to do this on more properties hence was looking for a generic way. Currently while it reaches for value {"a": "b"} it says that it can't find a instantiator for object with String.

**Comment by yawkat** [comment]
there is no built-in way to do this.

**Comment by anuragagarwal561994** [comment]
I have for now handled it somehow:
```
    @Override
    public Object handleMissingInstantiator(DeserializationContext ctxt, Class<?> instClass,
        ValueInstantiator valueInsta, JsonParser p, String msg) throws IOException {
        var valueAsString = p.getValueAsString();
        try {
            return jsonMapper.readValue(valueAsString, instClass);
        } catch (IOException e) {
            log.error("Error handling instantiation: {}", e.getMessage());
            return super.handleMissingInstantiator(ctxt, instClass, valueInsta, p, msg);
        }
    }
```

This is under `DeserializationProblemHandler` but do you think that combining support can be a use case.

Like I can imagine, csv, yamls and properties to have json texts as well as values.

**Comment by yawkat** [comment]
ObjectMappers support only a single data format. That would be difficult to change. This problem can only be solved by combining multiple mappers, but that has its own difficulties (separate configs) so in my opinion support for this should not be provided for such a niche use case.

**Comment by anuragagarwal561994** [comment]
Yeah I know and that makes sense as well, do you think a simpler fallback way can be thought of. For now this is working for me, so we can close the issue unless this needs to be discussed.

**Comment by cowtowncoder** [comment]
I agree with all of above: this is a sort-of known wish, but I haven't thought of a good way to support such composition: different format-specific mappers cannot really have dependencies to each other (at library level); all have some state (separate parser/generator to use).
It's something that could be discussed at:

https://github.com/FasterXML/jackson/discussions

For now I will close this issue.
