### ISSUE TITLE
Query on Jackson-dataformat-yaml usage

### ISSUE THREAD

**Issue by rongaliramunaidu** [FasterXML/jackson-dataformats-text#432]
Hi ,

 I see that Jackson-dataformat-yaml project is archived now and it is moved to jackson-dataformats-text. But there is an option to download the jar for Jackson-dataformat-yaml separately from jackson-dataformats-text. Do you force any issue if we take Jackson-dataformat-yaml jar and use it instead of jackson-dataformats-text? I am already using older version of Jackson-dataformat-yaml jar.

Thanks & Regards, Ramunaidu

**Comment by yawkat** [comment]
jackson-dataformats-text is the parent project, it has no jar, only a pom. `com.fasterxml.jackson.dataformat:jackson-dataformat-yaml` is the right maven coordinate for the current releases.

**Comment by cowtowncoder** [comment]
In addition to what @yawkat said the original stand-alone repo for `jackson-dataformat-yaml` is indeed deprecated; it was deprecated when most textual format backends (not including `jackson-dataformat-xml`) where brought into one multi-module project (for easier release process, less work per module).

Name of format module was not changed, just organization of code.
