### ISSUE TITLE
Weird issue with dates

### ISSUE THREAD

**Issue by dabaus** [FasterXML/jackson-dataformats-text#461]
I create my mapper:
```
private static final CsvMapper CSV_MAPPER = new CsvMapper();

static {
    CSV_MAPPER.configure(CsvGenerator.Feature.STRICT_CHECK_FOR_QUOTING, true);
    CSV_MAPPER.registerModule(new JavaTimeModule());
}

```

I set up my csv schema like this
```
final CsvSchema csvSchema = CSV_MAPPER
    .schemaFor(MyCsvOutputRow.class)
    .withHeader()
    .withColumnSeparator('|')
    .withNullValue("")
    .withLineSeparator("\r\n");
```

And then i  do something like

```
try (SequenceWriter csvWriter = CSV_MAPPER.writer(csvSchema).writeValues(writer)) {
    for (var entry : myEntries) {
        final MyCsvOutputRow row = ...
        csvWriter.write(row);
    }
}
```
        
  
My problem is that with this setup, whenever i have a date for example 2024-01-30  it gets encoded as 2024;1;30. And it does not seem to matter if i use  @JsonFormat or format it myself and pass it in as string. It still gets escaped.

What is causing this escape to happen?

**Comment by dabaus** [comment]
Never mind, i had forgotten a JsonFormat and for some reason ; was in the default format?

**Comment by cowtowncoder** [comment]
Yes, that output format suggests that code was trying to serialize value as Array, which gets encoded using semicolons by default (configurable but still).

But with CSV you definitely would want "as-String" instead. This goes to configuration of `JavaTimeModule`.
