### ISSUE TITLE
Allow CSV to differentiate between `null` and empty fields (foo,,bar vs. foo,"",bar)

### ISSUE THREAD

**Issue by PujolDavid** [FasterXML/jackson-dataformats-text#469]
I have not found any way to read a CSV that differentiate null and empty values.
I have played with various options and I also do a debug step by step in the jackson code.

The need is to be able to read a CSV generated by Postgres (and other apps) that make a difference between null and empty values.

Here an example of a 2 lines CSV:
foo,,bar
foo,"",bar

I expect to retrieve the following arrays:
["foo", null, "bar"]
["foo", "", "bar]

Can we add an option in CsvParser.Feature such as EMPTY_NON_QUOTED_STRING_AS_NULL?
This will also help to read CSV created with CsvGenerator.Feature.ALWAYS_QUOTE_EMPTY_STRINGS option

Thanks for taking time to read me.

**Comment by cowtowncoder** [comment]
While we are always open for improvements and suggestions, I am not quite sure about this one -- conceptually it seems to me that both cases should be the same. That is, quoting (or not) should not have effect on resulting value.

Having said that, if someone can implement the difference cleanly as PR (and enabled via `CsvParser.Feature`), I would accept the contribution.

**Comment by PujolDavid** [comment]
I made the following PR https://github.com/FasterXML/jackson-dataformats-text/pull/471

Note that this PR is done on version 2.18, but I will be happy to do the PR for previous version if accepted (I'm using 2.14/2.15 with Spring boot 3.0/3.1)

**Comment by cowtowncoder** [comment]
As per my notes on PR this feature will officially be added in 2.18(.0), but technically is merged into 2.17 branch so will be "dark launch"ed in 2.17.1, as a preview feature of sort.
This because it'll be a while until 2.18.0 is released.
