### ISSUE TITLE
how to append data in CSV

### ISSUE THREAD

**Issue by shoaibshaikh1516** [FasterXML/jackson-dataformats-text#48]
how to append data in CSV (JSON)

List list = new ArrayList<>();
list.add(populateLoginR());

	  CsvMapper mapper = new CsvMapper();
	  mapper.configure(JsonGenerator.Feature.IGNORE_UNKNOWN, true);
	   CsvSchema schema = CsvSchema.builder().addColumn("home_page").addColumn("message").addColumn("full_name").build();
	   ObjectWriter writer = mapper.writerFor(LoginR.class).with(schema);

	  File tempFile = new File("G://green pyramid//output.csv");
	    writer.writeValues(tempFile).writeAll(list);
	    System.out.println("Success");
	 }

	  private LoginR populateLoginR() {
		  LoginR o1 = new LoginR();
	  o1.setHomePage(lclasscatch.getHomePage());
	  o1.setMessage(lclasscatch.getMessage());
	  o1.setFullName(lclasscatch.getFullName());
	  

	  return o1;
	 }

**Comment by cowtowncoder** [comment]
In future, please use mailing list:

https://groups.google.com/forum/#!forum/jackson-user

for asking usage question. Issue tracker is not meant for that.

But in this case I think you are already using `SequenceWriter` (it's the thing that `writer.writeValues()` gives you). Just keep a reference to that, write more entries, and once you are done, `close` it?

```java
SequenceWriter seqw = writer.writeValues(tempFile).
seqw.writeAll(lost);
...
// and more items?
seq.write(someNewItem);
```

Alternatively, if you want to append to a `File`, you will need to create `FileOutputStream` yourself, specifying that you want to append (not replace), and pass that when creating `ObjectWriter`. You need to make sure not to write header (specify this in `CsvSchema` I think).

**Comment by shoaibshaikh1516** [comment]
can You give a complete/runnable example

**Comment by cowtowncoder** [comment]
@shoaibshaikh1516 Do your own homework. Look at unit test, perhaps, google, StackOverflow.

**Comment by firsovroman** [comment]
Maybe this simple example will be useful to someone in future.
```
  CsvMapper mapper = new CsvMapper();
  mapper.configure(JsonGenerator.Feature.IGNORE_UNKNOWN, true);
  
  CsvSchema schema = CsvSchema.builder().setUseHeader(true)
          .addColumn("id")
          .addColumn("name")
          .addColumn("age")
          .build();
  
  ObjectWriter writer = mapper.writerFor(UserDto.class).with(schema);
  SequenceWriter seqw = writer.writeValues(new FileWriter(csvOutputFile, true));
  
  seqw.writeAll(list);
  seqw.writeAll(list);
```
