### ISSUE TITLE
2.17.2 in graalvm - not found StreamWriteConstraints

### ISSUE THREAD

**Issue by orthlus** [FasterXML/jackson-dataformats-text#490]
Hello! I'm trying build spring boot graalmv native image with
```
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-yaml</artifactId>
    <version>2.17.2</version>
</dependency>
```
and see this error
`ClassNotFoundException: com.fasterxml.jackson.core.StreamWriteConstraints`

I'm checked `.class` file and sources class `com.fasterxml.jackson.dataformat.yaml.YAMLGenerator`:
There is import `StreamWriteConstraints` in `2.17.2` `.class`, but it's not in sources.

It succesfully builded when I decrease version to `2.15.4`.

There is my code for better understanding https://github.com/orthlus/infrastructure-management/commit/b4792bd3e315f46f4645dcf2f09fd3947bfb18ec

**Comment by cowtowncoder** [comment]
`StreamWriteConstraints` comes from `jackson-core`. Make sure that minor versions (at least) of `jackson-core` and `jackson-dataformat-yaml` are same.
Almost certainly issue with version mismatch.
