### ISSUE TITLE
(yaml) Duplicate key detection

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#5]
(from: https://github.com/FasterXML/jackson-dataformat-yaml/issues/61 by @andrey-polyakov)

I need keys in map structures to be checked for duplicates and rejected if found. How to enable this, of course, if it is implemented?

To be specific, I want to avoid overwriting of values in java.util.Map.

**Comment by larsga** [comment]
FWIW Jackson 2.8.6 supports the `JsonParser` flag. I just tested a YAML file with a duplicate key and got this exception:

```
Caused by: com.fasterxml.jackson.core.JsonParseException: Duplicate field 'Everything'
 at [Source: java.io.BufferedInputStream@621319fd; line: 7, column: 11]
	at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:204)
	at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:198)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:367)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:708)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:505)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:362)
	at com.fasterxml.jackson.module.scala.deser.UnsortedMapDeserializer.deserialize(UnsortedMapDeserializerModule.scala:76)
	at com.fasterxml.jackson.module.scala.deser.UnsortedMapDeserializer.deserialize(UnsortedMapDeserializerModule.scala:39)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2915)
```

So I think this issue can be closed.

**Comment by cowtowncoder** [comment]
@larsga Thank you for checking that -- I went ahead and added a unit test to confirm this, and guard against regression.

**Comment by nagarajasr** [comment]
it doesn't seem to work for me.

jackson-dataformat-yaml:2.9.2
jackson-databind:2.9.3

here is the code:
```
ObjectMapper objMapper = new ObjectMapper(new YAMLFactory()).enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION); 
		reader = objMapper.readerFor(ResponseParameterGroup[].class);
```

here is my YAML. The second 'response_parameters' seems to override the first one, while i expect an exception to occur:

```
- parameter_group_name: GROUP1 ## there are several groups showing just one for brevity
  response_parameters: 
  - parameter_name: ObjectKey
    output:
      output_type: value
      output_name: name
    filters:
      - filter_type: object_type_filter
        filter_params:
          object_type: shelf
      - filter_type: data_filter
        filter_params:
            object_type: shelf
            criteria_name: type
            criteria_value: CPE1
  response_parameters:  ## this is the duplicate but i dont get any errors, this one seems to override the previous one
  - parameter_name: ObjectKey
    output:
      output_type: value
      output_name: name
    filters:
      - filter_type: object_type_filter
        filter_params:
          object_type: shelf
      - filter_type: data_filter
        filter_params:
            object_type: shelf
            criteria_name: type
            criteria_value: CPE2
```

what am i doing wrong?

**Comment by cowtowncoder** [comment]
I think I'd need to see definition of `ResponseParameterGroup`, and call to read value(s) (you did include `ObjectReader` but just need to see how it is called).

**Comment by nagarajasr** [comment]
hope this helps: 
```
https://gist.github.com/nagarajasr/5c732575094601e678524d4a978cb865
```
DataPopulatorInputEntity is an empty marker interface.

and call to read values is along these lines:
```
public class DataPopulatorInputHelper<T extends DataPopulatorInputEntity> {
    public T[] getInputRecords(Reader dpifr) throws DataPopulatorException {
		T[] inputRecords = null;

		try {
			inputRecords = reader.readValue(dpifr);
		} catch (....) {
                      // handle exceptions
                }
    }
}
```

**Comment by cowtowncoder** [comment]
Ok. since it seems there is a remaining problem could you please file a new issue, for dup detection not working?
Ideally it'd be great to have simplified test case; I don't think complexity of model should matter here.

**Comment by Hzj-jie** [comment]
Just in case someone reaches this page from google. Same case here, YAMLFactory -> ObjectMapper -> JsonNode, DeserializationFeature.FAIL_ON_READING_DUP_TREE_KEY works. It's reasonable to be controlled by a deserialization feature, as you do not "parse" json, but "deserialize" objects from YAML parser.

**Comment by cowtowncoder** [comment]
@Hzj-jie ah! Thank you for pointing that out, that should be helpful.
