### ISSUE TITLE
(yaml) Empty string serialized without quotes if MINIMIZE_QUOTES is enabled

### ISSUE THREAD

**Issue by tim-palmer** [FasterXML/jackson-dataformats-text#50]
YAMLGenerator does not quote empty strings if MINIMIZE_QUOTES is enabled.

The YAML 1.2 spec says that [plain (unquoted) scalars cannot be empty](http://yaml.org/spec/1.2/spec.html#id2788859) i.e. an empty string must always be quoted.

```
      YAMLFactory f = new YAMLFactory();
      f.configure(YAMLGenerator.Feature.MINIMIZE_QUOTES, true);

      YAMLMapper mapper = new YAMLMapper(f);

      Map<String, Object> content = new HashMap<>();
      content.put("key", "");
      String yaml = mapper.writeValueAsString(content).trim();

      assertEquals("---\nkey: \"\"", yaml); // fails - actual output is "---\nkey:"
```

**Comment by cowtowncoder** [comment]
That sounds like SnakeYAML problem, since it is used for generation.
Is this with the latest version? (2.9.2)

**Comment by tim-palmer** [comment]
Yes - I am using 2.8.9 but I can also reproduce the issue with 2.9.2.

**Comment by cowtowncoder** [comment]
Fwtw, looks like there is one more release of `SnakeYAML`, 1.19:

https://bitbucket.org/asomov/snakeyaml/wiki/Changes

which could have a relevant fix. I did not see any issue that seemed related, but I can test locally.

**Comment by cowtowncoder** [comment]
Added a failing tests, reproduces with 2.9, 3.0.0-SNAPSHOT. Newer version of `SnakeYAML` does not make difference here.

**Comment by asomov** [comment]
You mention YAML 1.2 spec. 

SnakeYAML supports YAML 1.1

**Comment by cowtowncoder** [comment]
@asomov Ah. Good point, I added explicit mention of 1.2 in description.

I wonder if forced quoting might be useful, still, even without requiring 1.2 compliancy.
