### ISSUE TITLE
`null` Object Id serialized as anchor for YAML

### ISSUE THREAD

**Issue by jflefebvre06** [FasterXML/jackson-dataformats-text#63]
Bug detected into com.fasterxml.jackson.databind.ser.impl.WritableObjectId#writeAsField

gen.writeObjectId(String.valueOf(id));

shoud be if(id!=null)gen.writeObjectId(String.valueOf(id));

**Comment by cowtowncoder** [comment]
Any chance you could write a test case to show the problem? I agree that fix sounds legit, but I am trying to figure out where does the `null` id come from. Why is caller not suppressing such a call?

**Comment by jflefebvre06** [comment]
Yes of course, please find the belowed test.

[Issue63Test.zip](https://github.com/FasterXML/jackson-dataformats-text/files/1603244/Issue63Test.zip)

**Comment by jflefebvre06** [comment]
@cowtowncoder Hello, do you reproduce with my sample ?

**Comment by cowtowncoder** [comment]
@jflefebvre06 Thank you for reminder! Unfortunately I haven't had time to look into this, but I now added it on Work-in-progress page:

https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress

to improve chances I'll get here soon. Apologies for delays.

**Comment by jflefebvre06** [comment]
Works fine thank you

**Comment by cowtowncoder** [comment]
@jflefebvre06 thank you for verification.
