### ISSUE TITLE
YAMLParser#createParser doesn't not close FileInputStream

### ISSUE THREAD

**Issue by jflefebvre06** [FasterXML/jackson-dataformats-text#64]
@Override
    public YAMLParser createParser(File f) throws IOException {
        IOContext ctxt = _createContext(f, true);
        return _createParser(_decorate(new FileInputStream(f), ctxt), ctxt);
    }

**Comment by cowtowncoder** [comment]
Internal `FileInputStream` should be closed if `YAMLParser` instance is `close()`d (or if stream reaches end). So I think I would need a test case so otherwise at this point.
