### ISSUE TITLE
When field names are reserved words, they should be written out with quotes

### ISSUE THREAD

**Issue by baconmania** [FasterXML/jackson-dataformats-text#68]
https://github.com/FasterXML/jackson-dataformat-yaml/blob/master/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.java specifies that YAML keys will always be written with `STYLE_NAME`, e.g. without quotes.
```java
    // for field names, leave out quotes
    private final static Character STYLE_NAME = null;
...
    private final void _writeFieldName(String name)
        throws IOException
    {
        _writeScalar(name, "string", STYLE_NAME);
    }
```

But this breaks parsers when you write a map with a key that is a reserved word in YAML, e.g. `no`. If `_writeFieldName()` encounters a field that is one of `{ y, true, yes, on, n, false, no, off }`, it should use `STYLE_QUOTED`.

Actual definition of such boolean values can be found here:

https://yaml.org/type/bool.html

**Comment by cowtowncoder** [comment]
Thank you for reporting this, contributing patch.

Bit odd that SnakeYAML does not do escaping. But as with everything, looks like YAML has gone off the deep end with the rather long list of reserved names.... so maybe it's impractical.

**Comment by baconmania** [comment]
Thanks for the quick response!

And yeah, YAML's actual spec is [chaos](http://www.yaml.org/spec/1.2/spec.html):

```txt
The content of a mapping node is an unordered set of key: value node pairs, with the restriction that
each of the keys is unique. YAML places no further restrictions on the nodes. In particular, keys may be
arbitrary nodes, the same node may be used as the value of several key: value pairs, and a mapping
could even contain itself as a key or a value (directly or indirectly).
```

Given that, the minimal-change way to support reserved-words keys without actually implementing the full YAML spec in Jackson's writer is adding a feature to just quote all keys.

But hey, I'll ask you one favor: would you able to backport this to jackson-dataformat-yaml 2.7.x (or at least 2.7.9)?

**Comment by cowtowncoder** [comment]
@baconmania Wrt 2.7, unfortunately no. If I followed semantic versioning strictly, this could even go in 2.9 being new feature. But since that branch is open and likely the last 2.x version I don't have problem doing that. However backporting is different story -- 2.7 in particular is closed and only "micro-patches" are to be release (like 2.7.9.1) for critical bugs.

Thank you for feature PR itself; I'll add just one note there.

**Comment by cowtowncoder** [comment]
@baconmania I actually decided to try to add only-if-needed quoting, and not yet adding new feature to force quoting. Happy to add such feature if it's needed of course.

Will finally be in 2.9.9 and 2.10.0.
