### ISSUE TITLE
Configurable _cfgMaxQuoteCheckChars

### ISSUE THREAD

**Issue by QubitPi** [FasterXML/jackson-dataformats-text#72]
Is there anyway for downstream projects to configure value of `_cfgMaxQuoteCheckChars`? We don't want string longer than 24 to be quoted 
https://github.com/FasterXML/jackson-dataformats-text/blob/master/csv/src/main/java/com/fasterxml/jackson/dataformat/csv/impl/CsvEncoder.java#L194

**Comment by cowtowncoder** [comment]
Nope. Cut-off level could be made configurable in 3.0, but at this point there is no mechanism for adding that.

In future, please use mailing lists for asking usage questions:

https://groups.google.com/forum/#!forum/jackson-user
