### ISSUE TITLE
Is it possible to write list of maps

### ISSUE THREAD

**Issue by solairerove** [FasterXML/jackson-dataformats-text#73]
In example i saw maps due mapping iterator for reading. It's reale cool to write csv due `List<Map<Object>>`

**Comment by cowtowncoder** [comment]
@solairerove for future reference, please use mailing list

https://groups.google.com/forum/#!forum/jackson-user

for usage question.

But yes, there is `writeValues()` in `ObjectWriter` (which can be constructed from `ObjectMapper`), and that exposes `SequenceWriter` (I think) for doing just that.
