### ISSUE TITLE
`JavaPropsMapper` issue deserializing multiple byte array properties

### ISSUE THREAD

**Issue by spifd** [FasterXML/jackson-dataformats-text#74]
Hi,

I've found an issue: byte array values look not correctly set when having multiple `byte[]` in a data model. When it happens, the same byte array content is set to ALL of the bean `byte[]` (or ByteBuffer) properties. I even have a more complex use case where an object property is set with the deserialized value of another different object `byte[]` property.

Please see the simple test case attached.
Fabrice

[MyBean.java.zip](https://github.com/FasterXML/jackson-dataformats-text/files/1747744/MyBean.java.zip)

**Comment by cowtowncoder** [comment]
@spifd Thank you for reporting this. I'll have a look.

**Comment by cowtowncoder** [comment]
Decoded binary value was not being cleared appropriately. Fixed now, for 2.9.5, thank you for reporting this!
