### ISSUE TITLE
(csv) ObjectWriter.writeValues() writing out header for each call

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#8]
(from https://github.com/FasterXML/jackson-dataformat-csv/issues/148 by @bhchandra )

This is related to:  writeValue writes out header in each call. #71 which is closed.

The following was mentioned in the page.

"_But I think what you may really want to use is the new method(s) added in 2.5: ObjectWriter.writeValues() (http://fasterxml.github.io/jackson-databind/javadoc/2.5/com/fasterxml/jackson/databind/ObjectWriter.html#writeValues%28java.io.OutputStream%29).
It returns a SequenceWriter which has write and writeAll methods to use.
That should properly handle headers; and if not, that would definitely be a bug_".

I am not sure, please take a look at this code.

```
                csvMapper.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);
                fileStream = Files.newOutputStream(this.path, CREATE, WRITE, APPEND);
                jsonGenerator = csvMapper.getFactory().createGenerator(fileStream);

                //Works Good. Doesn't write header for each call
                csvMapper.writer(schema).writeValue(jsonGenerator, data);   
  
                //Writes header for each call.        
                csvMapper.writer(schema).writeValues(fileStream).write(data);
```

"_In the end use of ObjectWriter.writeValues() is the recommended method, and the proper resolution_"

I want to use writeValues() since it is the recommended.
Please resolve if I am making some mistake in code or this is a bug?
using 2.8.7.

**Comment by bhchandra** [comment]
Data is a POJO, which consists of Strings, a enum, and ZoneDateTime.

I also, have the required modules registered.

`csvMapper.registerModules(new JavaslangModule(), new Jdk8Module(), new JavaTimeModule(), new AfterburnerModule());
`

**Comment by cowtowncoder** [comment]
@bhchandra Ok. Just wanted to make sure. I don't think exact details matter as much, just that it's a POJO with multiple scalar-valued properties. About the only possible complication from setup could be afterburner module (since it can change calls), but even that seems unlikely to be the root cause.

What I really need to figure out is just how to reproduce the issue with as simple a test as possible.
I think there are unit tests for usage, but better double-check.

**Comment by cowtowncoder** [comment]
Ok so there are tests, but they are bit simplistic (incuding ones for #71). I'll see if I can improve upon them and reproduce your issue.
Thank you for reporting the problem.

**Comment by bhchandra** [comment]
My use case is: I am reading a csv file and I need to classify each record and drop it into different new csv files. I read the file line by line and use 
```
                streamOfRecords.forEach(pojo-> 
                {
                    
                    if( Predicate.test(pojo) ){ Writer.write(pojo); }
                    '
                    '
                    '
                                   
                })

```

The write method:
```
 public  void write(POJO data){
            try{
                csvMapper.writer(schema).writeValue(jsonGenerator, data);
           //csvMapper.writer(schema).writeValues(fileStream).write(data);
                jsonGenerator.flush();
             //fileStream.flush();
            } catch (IOException ex) {
                logger.error(ex.toString());
            }
        }
```

Reading is also done through jackson.

**Comment by cowtowncoder** [comment]
It definitely should work -- I hope to have to look into this.

**Comment by cowtowncoder** [comment]
I can not reproduce this problem with `writeValues()`. However, I wonder if there is misunderstanding on usage here. `writeValues()` should only ever be called once, to create `SequenceWriter`; first write on this writer will write header, but further calls should not.

So I think what I really need is a self-contained reproduction of the problem.

**Comment by bhchandra** [comment]
> writeValues() should only ever be called once

Understood. Thank you. 
You are awesome. Have an awesome day.

**Comment by shoaibshaikh1516** [comment]
how to append data in CSV 

List list = new ArrayList<>();
		  list.add(populateLoginR());
		 
		 
		  CsvMapper mapper = new CsvMapper();
		  mapper.configure(JsonGenerator.Feature.IGNORE_UNKNOWN, true);
		   CsvSchema schema = CsvSchema.builder().addColumn("home_page").addColumn("message").addColumn("full_name").build();
		   ObjectWriter writer = mapper.writerFor(LoginR.class).with(schema);

		  File tempFile = new File("G://green pyramid//output.csv");
		    writer.writeValues(tempFile).writeAll(list);
		    System.out.println("Success");
		 }

		  private LoginR populateLoginR() {
			  LoginR o1 = new LoginR();
		  o1.setHomePage(lclasscatch.getHomePage());
		  o1.setMessage(lclasscatch.getMessage());
		  o1.setFullName(lclasscatch.getFullName());
		  

		  return o1;
		 }
