### ISSUE TITLE
Release 2.9.6 to Maven Central

### ISSUE THREAD

**Issue by dszakallas** [FasterXML/jackson-dataformats-text#89]
We face an error when trying to resolve jackson-dataformat-csv-2.9.6

```
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.6/jackson-dataformat-csv-2.9.6.pom: Impossible to load parent for file:/Users/dszakallas/.ivy2/cache/com.fasterxml.jackson.dataformat/jackson-dataformat-csv/ivy-2.9.6.xml.original. Parent=com.fasterxml.jackson.dataformat#jackson-dataformats-text;2.9.6
```

It seems like `jackson-dataformats-text;2.9.6` is missing.

See
https://search.maven.org/#search|ga|1|jackson-dataformats-text
(latest is 2.9.5)

https://search.maven.org/#search%7Cga%7C1%7Cjackson-dataformat-csv
(latest is 2.9.6)

and jackson-dataformats-csv 2.9.6 specifies jackson-dataformats-text 2.9.6 as parent: https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.6/jackson-dataformat-csv-2.9.6.pom

**Comment by cowtowncoder** [comment]
Once again, Maven Central managed to broke this somehow, despite reporting successful release with maven release plugin :-( :-( :-(

Thank you for reporting this.

**Comment by rgoldberg** [comment]
The following artifact also cannot be found in Maven Central:

    com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.6

The 2.9.5 yaml version can be found, and 2.9.5 & 2.9.6 annotations, core & databind are correctly found.

If I just need the yaml data format (and I don't need csv, xml, properties, etc.), what is the recommended Maven dependency (for use from Gradle)?

**Comment by cowtowncoder** [comment]
I pushed update of `jackson-dataformats-text`, and despite Nexus being very slow today (possibly related to corrupted upload), I _think_ it should be heading to MC. Will keep an eye on it; I do a have test project with deps and it sort of reported the problem -- except I did not realise it was "parent" pom missing as error was for CSV module... which itself was correctly released it seems.

**Comment by dszakallas** [comment]
Thanks!
