### ISSUE TITLE
Writing CSV headers only [feature request?]

### ISSUE THREAD

**Issue by nakamorichi** [FasterXML/jackson-dataformats-text#92]
I have a case when there might be no actual input, but I still want to output an empty CSV file containing the headers. Due to the streaming nature, I don't know beforehand whether there will be input objects or not, so I want to write the headers first. Is there a way to get the headers as a String, byte[], etc.?

EDIT: found a way to get the header as a string, but surely there's a better way?
```java
List<String> columns = new ArrayList<>();
CsvSchema schema = mapper.typedSchemaFor(klass);
schema.forEach(column -> columns.add(column.getName()));
String headerStr = String.join(",", columns) + "\n";
```

**Comment by cowtowncoder** [comment]
@Kitanotori I agree in that it seems like a reasonable thing to be able to write "empty" files, i.e. just header line, no data lines.

Does this not work by using `SequenceWriter` (creating `ObjectWriter` from mapper, then `SequenceWriter` with `writeValues()` method), and by simply creating, closing it without writing any entries?

**Comment by amr** [comment]
@cowtowncoder I was able to confirm that doing what you suggested does indeed write the header. Thanks for the tip!

Would be nice of course if this was provided explicitly through the API somehow.

**Comment by dabaus** [comment]
Was this ever added? I have similar case where i want to write csv but in a streaming way.
So i need to get the header first.

**Comment by cowtowncoder** [comment]
@amr That is via API, fwtw. But I guess you mean something like a convenience method or so.
