### ISSUE TITLE
property value is truncated to 40 characters

### ISSUE THREAD

**Issue by gnplescan** [FasterXML/jackson-dataformats-text#95]
Hello,
I tried using the properties dataformat, and in my test I find that the mapped property value is truncated to 40 characters.

Example:
foo.bar: Loremipsumdolorsitametconsecteturadipiscingelit
This is be mapped to a String in my POJO with value "Loremipsumdolorsitametconsecteturadip...".

Is this an issue with my test or with the mapper?
Thanks.

**Comment by cowtowncoder** [comment]
What dataformat? With which Jackson version? With what code?

Please include a reproduction showing how truncation occurs: there are no known problems like this reported.
